ipfs-force-community/damocles

venus-sector-manager/dep/sealer.go

missing type: *modules.SafeConfig  for `BuildMarketAPI`

fix: missing type: *modules.SafeConfig error in command `util chain head`

---

venus-sector-manager/api/types_sector_state.go

fix: deal ids should only collect non-zero ones

---

venus-worker/src/sealing/worker/task/event.rs
venus-worker/src/sealing/worker/task/planner/sealer.rs

- 将请求 ticket 的步骤放在 pc1 内，避免预请求而无法顺利完成的情况下，ticket 超时。resolve #84 
- 将原 `TreeDBuilt` 对应的处理函数变为一个空步骤，以兼容原状态序列

feat(venus-worker): ask for ticket when needed

---

venus-sector-manager/modules/impl/sectors/snapup_commit.go

fix(vsmgr): ignore incompleted upgrade sectors

---

venus-worker/.cargo/config.toml
venus-worker/Cargo.lock
venus-worker/Cargo.toml
venus-worker/Makefile
venus-worker/src/logging/mod.rs

venus_worker 日志输出时使用本地时区输出时间. 
related issue: #87
经过调研，决定启用 `unsound_local_offset` flag. 根据 [time crate issue #293](https://github.com/time-rs/time/issues/293) 说明: 获取本地时区会调用 `libc::localtime_r`, 而此函数在多线程情况下可能会发生 `data race`. 
我使用 [`tracing_subscriber::fmt::time::OffsetTime`](https://docs.rs/tracing-subscriber/0.3.11/tracing_subscriber/fmt/time/struct.OffsetTime.html) 代替 [`tracing_subscriber::fmt::time::LocalTime`](https://docs.rs/tracing-subscriber/0.3.11/tracing_subscriber/fmt/time/struct.LocalTime.html) 作为日志时间的 Fomater. 
[`tracing_subscriber::fmt::time::OffsetTime`](https://docs.rs/tracing-subscriber/0.3.11/tracing_subscriber/fmt/time/struct.OffsetTime.html) 会在构造时获取本地时区并保存，不会[每次输出日志时间的时候获取时区](https://docs.rs/tracing-subscriber/0.3.11/src/tracing_subscriber/fmt/time/time_crate.rs.html#184 …

feat(log): use local time zone instead of UTC time zone for log output

---

venus-worker/Makefile

resolved #156 
closed #180 
venus-worker 的 Makefile 中增加对已经形成习惯的 `FFI_USE_CUDA` 进行支持

chore: makefile of venus-worker now support env FFI_USE_CUDA

---

docs/zh/05.快速启用.md
venus-worker/Cargo.lock
venus-worker/Cargo.toml
venus-worker/src/bin/venus-worker/store.rs
venus-worker/src/bin/venus-worker/store/shm.rs
venus-worker/vc-processors/Cargo.toml
venus-worker/vc-processors/src/fil_proofs/mod.rs
venus-worker/vc-processors/src/lib.rs
venus-worker/vc-processors/src/sys/mod.rs
venus-worker/vc-processors/src/sys/numa.rs

resolve #85 
related PR: ipfs-force-community/rust-fil-proofs#1, ipfs-force-community/rust-fil-proofs#2
1. 将 rust-fil-proofs 相关依赖替换为 [ipfs-force-community/rust-fil-proofs](https://github.com/ipfs-force-community/rust-fil-proofs/tree/force/master_v11.1.1) 该分支支持使用共享内存
2. 新增 NUMA 函数绑定
3. worker 新增 `./worker store shm-init` 子命令用于创建共享内存文件

feat(worker): support for NUMA aware when creating PC1 label memory

---

venus-worker-util/Cargo.lock
venus-worker-util/Makefile

fix #341
升级 hwloc2 解决获取 NUMANode 时可能的空指针问题。
hwloc2 改动: https://github.com/ipfs-force-community/hwloc2-rs/commit/93167d3b8add176cd2b8a81797c8f4680ef9d472

fix(hwinfo): upgrade hwloc2 lib to solve the null pointer

---

docs/zh/14.venus-sector-manager的mertics使用.md
venus-sector-manager/cmd/venus-sector-manager/server.go
venus-sector-manager/go.mod
venus-sector-manager/metrics/exporter.go
venus-sector-manager/metrics/metrics.go
venus-sector-manager/metrics/proxy/proxy.go
venus-sector-manager/metrics/re_export.go
venus-sector-manager/modules/sealer/sealer.go

resolve #339 
resolve #340 
venus-cluster中vsmgr部分引入mertics框架：
1. 在rpc端口上加入`/mertics`用于export mertics
2. vcs接口级别的时间mertics
3. 对于扇区的流程在关键处（新建，precommit，provecommit）加入计数
4. prover侧对于proof的产生时间的mertics
5. 当前服务的miner在当前deadline结束前20个高度会产生windowpost的完成率

feat(vsmgr:mertics): import metrics & add some view

---

docs/en/04.venus-sector-manager-config.md
docs/zh/04.venus-sector-manager的配置解析.md
venus-sector-manager/dep/miner.go
venus-sector-manager/dep/sealer_constructor.go
venus-sector-manager/dep/util.go
venus-sector-manager/dep/util_test.go

resolve #358 
- 提供一种可以为每一个单一 rpc 服务（实例）配置独立的 token 的方式

feat(vsmgr): support token-included api infos

---

venus-worker/Cargo.lock
venus-worker/Cargo.toml
venus-worker/src/bin/venus-worker/processor/mod.rs
venus-worker/vc-processors/src/fil_proofs/mod.rs

fix #414
vc-processors 中导出的 init_numa_mem_pool 函数移动到 venus-worker 中

fix(worker): move fn init_numa_pool out of vc_porcessors

---

venus-sector-manager/cmd/venus-sector-manager/internal/util_worker.go
venus-sector-manager/core/worker.go
venus-worker/src/bin/venus-worker/worker/mod.rs
venus-worker/src/rpc/worker/mod.rs
venus-worker/src/sealing/service.rs
venus-worker/src/sealing/worker/ctrl.rs
venus-worker/src/sealing/worker/task/mod.rs
venus-worker/src/sealing/worker/task/planner/mod.rs

resolve #428
venus-sector-manager util worker info  和 venus-worker worker list 增加 plan 列

feat(cli): show sealing_thread plan

---

venus-worker/src/sealing/worker/task/planner/sealer.rs

#362 
当前 sealer planner 申请新扇区仅仅只需要满足扇区号规则等限制。因此无法按照预期进入 idle 状态。
考虑在申请 deals 时，若未获取到 deals 则进入 idle状态，使得有机会退出任务循环重新加载热配置文件。
当 sealer planer 获取不到 deals 时，进入 Idle 状态。
1. cc 扇区任务会在封装完成后退出 task 从而有机会重新加载热配置文件
2. acquire_deals rpc 请求不重试多次，一旦没有deals 直接进入 Idle， 因为从语义上来说没有 deals 确实属于 idle， 并且 Task 循环在接收到 Event::Idle 事件时也会重试 `request_task_max_retries` 次

fix(worker): idle if no deals

---

.github/workflows/venus-worker-util.yaml
.github/workflows/venus-worker.yaml

ref #214 
- venus-worker CI 缓存整个 `~/.cargo` 目录。避免重复编译工作
- 保护分支开启 push 触发 ci。主要用于生成缓存，也能保证保护分支的代码是通过ci的。
- venus-worker-util 移除了action 缓存。venus-worker-util 编译速度比较快，移除缓存节约缓存的空间。
尝试 [sccache](https://github.com/mozilla/sccache) 后编译速度提升不明显，所以放弃 sccache。
参考: 
- https://www.infinyon.com/blog/2021/04/github-actions-best-practices/
- https://github.com/mozilla/sccache#github-actions
- https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache
- https://doc.rust-lang.org/cargo/guide/cargo-home.html#caching-the-cargo-home-in-ci

chore(CI): fix cargo cache

---

venus-sector-manager/cmd/venus-sector-manager/internal/util_miner.go
venus-sector-manager/cmd/venus-sector-manager/internal/util_sealer_actor.go

close #531 
close #418
close #419
close #420
提币命令增加提取至受益人地址选项，增加收益人指定和确认功能，打印受益人地址

feat(vsmgr): vsmgr support beneficiary address operation

---

venus-sector-manager/cmd/venus-sector-manager/internal/util_sealer_sectors.go

closes #391, closes #567, closes #578
- add sectors renew/extend --only-cc flag
- add renew max-sectors flag
- removes extend subcommand
- renames renew to extend. also includes some minor refactoring

feat(vsm: cli): Refactor renew and remove extend

---

venus-sector-manager/cmd/venus-sector-manager/internal/global.go
venus-sector-manager/cmd/venus-sector-manager/main.go

声明 `--net` flag 已弃用，启动 vsm 时带了 `--net` flag 不会报错，而是打印一条警告。

chore(vsm: cli): make `--net` flag deprecated

---

venus-worker/Cargo.lock
venus-worker/Makefile
venus-worker/src/config.rs

* 降级 time crate 版本，修复 tracing-subscriber 日志的 `<unknown time>` bug
* toml 在配置文件输出时不支持 u128, 所以配置文件格式化打印从 toml 格式改为 rust 自带的格式化输出

fix(worker): downgrade the version of time crate to fix `unknown time` bug

---

damocles-manager/cmd/damocles-manager/internal/util_storage.go
damocles-manager/core/types.go
damocles-manager/dep/sealer_constructor.go
damocles-manager/go.mod
damocles-manager/go.sum
damocles-manager/modules/config.go
damocles-manager/modules/config_util_test.go
damocles-manager/modules/sealer/sealer_cli.go
damocles-manager/pkg/objstore/filestore/store.go
damocles-manager/pkg/objstore/mgr.go
damocles-manager/pkg/objstore/mgr_test.go
damocles-manager/pkg/objstore/mock_store.go
damocles-manager/pkg/piecestore/proxy.go
damocles-manager/pkg/piecestore/proxy_test.go
docs/zh/04.damocles-manager的配置解析.md
manager-plugin/objstore/objstore.go

close https://github.com/ipfs-force-community/damocles/issues/769
- 增加 `PieceStorePreset` 简化 PieceStore 的配置
- 支持  `lotus` 风格的存储配置文件

Feat  add preset to config of persist store

---

CHANGELOG.zh.md
damocles-manager/ver/ver.go
damocles-worker/Cargo.lock
damocles-worker/Cargo.toml

chore: release v0.8.0-rc1

---

CHANGELOG.zh.md
damocles-manager/core/types_wdpost.go
damocles-manager/ver/ver.go
damocles-worker/Cargo.lock
damocles-worker/Cargo.toml
docs/zh/09.独立运行的poster节点.md

- Cherry-pick PR #849 #850 to release/v0.8
- Release v0.8.0-rc2

Cherry pick #849 #850 to release/v0.8

---

damocles-manager/cmd/damocles-manager/internal/util_sealer_sectors.go

fix(manager): revert the sectors abort command

---

docs/en/09.poster-node.md
docs/zh/09.独立运行的poster节点.md

related https://github.com/ipfs-force-community/venus-core-devs/issues/18

update en 09 doc

---

CHANGELOG.zh.md
damocles-manager/go.mod
damocles-manager/go.sum
damocles-manager/modules/impl/sectors/proving.go
damocles-manager/ver/ver.go
damocles-worker/Cargo.lock
damocles-worker/Cargo.toml

- Cherry pick #924 to release/v0.8
- Cherry pick #926 to release/v0.8
- Release v0.8.3

Cherry pick #924, #926 to release/v0.8

---

CHANGELOG.zh.md
damocles-manager/modules/impl/sectors/snapup_commit.go
damocles-manager/ver/ver.go
damocles-worker/Cargo.lock
damocles-worker/Cargo.toml
damocles-worker/vc-processors/src/builtin/processors/piece/fetcher/http.rs

ref #1040 #1041
- Cherry-pick #1040 #1041 to release v0.9
- Release v0.9.1

Cherry-pick #1040 #1041 to release v0.9

---

CHANGELOG.zh.md
damocles-manager/dep/sealer_constructor.go
damocles-manager/modules/config.go

presist 存储没有配置Name字段的，提示多个 presist 重名，需要每个都加上 Name。这个 pr 修复了这个问题

fix: use Path as default Name if Name is empty string

---

CHANGELOG.zh.md
damocles-manager/dep/sealer.go

修复对 core.SealerCliAPIClient 错误的依赖注入，导致 damocles-manager 代理模式无法正常启动

fix(di): inject the `core.SealerCliAPIClient` correctly

---

CHANGELOG.zh.md
damocles-manager/modules/impl/commitmgr/precommit_processor.go
damocles-manager/modules/impl/prover/worker/job_mgr_kv.go
damocles-manager/ver/ver.go
damocles-worker/Cargo.lock
damocles-worker/Cargo.toml

- cherry pick #1055 #1056 to release/v0.9
- release v0.9.3

Cherry pick #1055 #1056 to release v0.9

---

CHANGELOG.zh.md
damocles-worker/src/config.rs
damocles-worker/src/sealing/config.rs
damocles-worker/src/sealing/sealing_thread/planner/common/sealing.rs
damocles-worker/src/sealing/sealing_thread/planner/sealer.rs
docs/en/03.damocles-worker-config.md
docs/zh/03.damocles-worker的配置解析.md

fix: enabling verify_pc2 will automatically abort task. because `pc2_out` is not correctly set to sector state

---

damocles-worker/src/sealing/sealing_thread/planner/mod.rs

temporarily disable ni-porep for Calinet testing

---

damocles-manager/modules/impl/commitmgr/commit_processor.go
damocles-manager/modules/impl/commitmgr/params.go
damocles-manager/modules/util/pledge/pledge.go

https://github.com/filecoin-project/lotus/pull/12341/files
调整 DDO 订单计算质押的逻辑

fix: Fix DDO pledge math
