- venus-worker/src/bin/venus-worker/processor/mod.rs
- venus-worker/src/lib.rs
- venus-worker/src/sealing/processor/external/sub/run.rs
- venus-worker/src/sealing/processor/mod.rs
- venus-worker/src/sealing/processor/safe.rs
实现 SnapDeal 相关的 processors， 并添加到命令行
> feat: impl snap related processors

- venus-sector-manager/api/api.go
- venus-sector-manager/api/client.go
- venus-sector-manager/cmd/venus-sector-manager/internal/util_sealer.go
- venus-sector-manager/modules/impl/mock/sealer.go
- venus-sector-manager/modules/impl/sectors/state_mgr.go
- venus-sector-manager/modules/sealer/sealer.go
- 实现 `RestoreSector` 接口
- 实现 CLI 命令 `util sealer sectors restore`
> feat: impl api RestoreSector & CLI cmd

- venus-sector-manager/modules/impl/dealmgr/dealmgr.go
> feat(venus-sector-manager:dealmgr): add a lock for acquiring deals

- CHANGELOG.zh.md
> chore: add content for v0.1.1 into changelog

- venus-sector-manager/modules/util/util.go
> fix(vsmgr:util): files in cache dir

- venus-worker/src/bin/venus-worker/store.rs
- venus-worker/src/bin/venus-worker/worker/mod.rs
- venus-worker/src/infra/objstore/filestore.rs
- venus-worker/src/logging/mod.rs
- venus-worker/src/sealing/store/mod.rs
- 使用一种更方便的写法处理日志中的 field 展示
- 移除不必要的重导出的项
> refacotr(venus-worker): remove usages of debug_field, remove unnecessary

- docs/zh/QA.md
> docs(QA): about compiled binary size

- CHANGELOG.zh.md
- venus-sector-manager/ver/ver.go
- venus-worker/Cargo.lock
- venus-worker/Cargo.toml
> Docs/dtynn/prepare for v0.2.0

- Makefile
- venus-sector-manager/Makefile
- venus-worker/Makefile
- 为 make dev-env 增加一些依赖工具的安装命令
> chore(Makefile): add more actions in command dev-env

- venus-worker/cleanup_orphan.sh
> chore: add a script for cleaning up orphan sub-groups in cgroup:cpuset

- CHANGELOG.zh.md
- venus-sector-manager/ver/ver.go
- venus-worker/Cargo.lock
- venus-worker/Cargo.toml
> Chore/dtynn/update brach release v0.3.0 to the latest

- .github/dependabot.yml
> chore(dependabot): add config file

- docs/zh/10.venus-worker任务管理.md
- resolve #177 
- 提供 venus-worker 自管理和 venus-sector-manager 管理 venus-worker 的相关文档
其中 state 的部分需要等待 #181 
> docs: venus-worker management

- venus-worker/Makefile
- 优化 Makefile 对于 `--cfg unsound_local_offset only when missing` 的处理
> chore(Makefile): add --cfg unsound_local_offset only when missing

- docs/zh/10.venus-worker任务管理.md
- docs/zh/11.任务状态流转.md
resolve #181 
- 关于 venus-worker 中任务状态和转换路线的说明
> docs: about states and transitions in venus-worker

- CHANGELOG.zh.md
> Docs/dtynn/changelog for v0.3.0 rc1

- CHANGELOG.zh.md
> fix(Changelog): typo

- .github/workflows/check-go-on-pr.yaml
- .github/workflows/check-rust-on-pr.yaml
- .github/workflows/compile-go-on-pr.yaml
- .github/workflows/compile-on-push.yaml.bak
- .github/workflows/compile-rust-on-pr.yaml
- Makefile
- venus-sector-manager/Makefile
- venus-worker/Cargo.toml
- venus-worker/Makefile
- venus-worker/src/sealing/resource.rs
- 将 rust crates 升级到 edition 2021
- 向 github actions 加入 test 相关项
> Chore/dtynn/add tests in GitHub actions

- venus-worker/src/sealing/resource.rs
- 取消了 测试用例中的上界检查，避免在极端（低配置CI）情况下的 [failure](https://github.com/ipfs-force-community/venus-cluster/runs/6649283063?check_suite_focus=true)
> fix(vworker): remove the upper bound check for elapsed in tests

- venus-worker/Cargo.lock
- venus-worker/vc-processors/Cargo.toml
resolve #169 
- 将 vc-processors 的版本号升级到 0.1.0
> chore(ver): vc-processors upgrade to 0.1.0

- .github/workflows/vc-processors-publish.yaml
- venus-worker/Cargo.lock
- venus-worker/Makefile
- venus-worker/vc-processors/Cargo.toml
- venus-worker/vc-processors/src/lib.rs
- 增加发布时激活的features，以便自动生成文档
- 增加文档中的连接
> Chore/dtynn/vc processors v0.1.1

- .github/ISSUE_TEMPLATE/enhancement.yml
> fix: description in issue template for enhancement

- .github/workflows/venus-sector-manager.yaml
- .github/workflows/venus-worker.yaml
- 取消 push 事件对应的 github-actions 执行
> chore: disable checks & builds to reduce costs

- venus-worker/Cargo.lock
- venus-worker/Cargo.toml
- venus-worker/src/infra/objstore/filestore.rs
- venus-worker/src/sealing/processor/external/sub/cgroup.rs
- venus-worker/src/sealing/processor/external/sub/mod.rs
- venus-worker/vc-processors/Cargo.toml
- venus-worker/vc-processors/src/core/ext/producer.rs
resolved #225 
在 MacOS 构建时关闭 `cgroup` 和 `numa` 功能，Linux 构建时不受影响
把 `numa` feature 从 vc-processors 的 default-features 中移除了
> chore(build): support building on MacOS

- venus-worker/Cargo.lock
- venus-worker/Cargo.toml
- venus-worker/src/infra/objstore/filestore.rs
- venus-worker/src/sealing/processor/external/sub/cgroup.rs
- venus-worker/src/sealing/processor/external/sub/mod.rs
- venus-worker/vc-processors/Cargo.toml
- venus-worker/vc-processors/src/core/ext/producer.rs
Reverts ipfs-force-community/venus-cluster#227
> Revert "chore(build): support building on MacOS"

- venus-worker/Cargo.lock
- venus-worker/Cargo.toml
- venus-worker/src/infra/objstore/filestore.rs
- venus-worker/src/sealing/processor/external/sub/cgroup.rs
- venus-worker/src/sealing/processor/external/sub/mod.rs
- venus-worker/vc-processors/Cargo.toml
- venus-worker/vc-processors/src/core/ext/producer.rs
resolved #225 
在 MacOS 构建时关闭 `cgroup` 和 `numa` 功能，Linux 构建时不受影响
把 `numa` feature 从 vc-processors 的 default-features 中移除了
> chore(worker build): support building on MacOS

- venus-sector-manager/dep/sealer_constructor.go
- venus-sector-manager/modules/miner/proof_event_client.go
- venus-sector-manager/pkg/chain/api.go
- venus-sector-manager/pkg/market/api.go
- venus-sector-manager/pkg/messager/api.go
> fix:add retry option

- venus-sector-manager/ver/ver.go
- venus-worker/Cargo.lock
- venus-worker/Cargo.toml
> chore(ver): upgrade to 0.3.0-rc2

- docs/zh/QA.md
- venus-sector-manager/modules/impl/sectors/state_mgr.go
- venus-sector-manager/modules/poster/scheduler.go
- venus-worker/src/config.rs
- venus-worker/src/rpc/mod.rs
- venus-worker/src/sealing/failure.rs
- venus-worker/src/sealing/worker/task/planner/sealer.rs
- venus-worker/src/sealing/worker/task/planner/snapup.rs
- venus-worker/vc-processors/examples/sqr-consumer.rs
- venus-worker/vc-processors/examples/sqr-producer.rs
- venus-worker/vc-processors/src/builtin/tasks.rs
- venus-worker/vc-processors/src/core/ext/producer.rs
- venus-worker/vc-processors/src/lib.rs
- venus-worker/vc-processors/src/sys/numa.rs
> fix(typo): fix some typo

- venus-worker/src/sealing/processor/external/sub/mod.rs
> fix(vc-worker): avoid cgroup dropped unexpectedlly

- docs/zh/03.venus-worker的配置解析.md
- docs/zh/04.venus-sector-manager的配置解析.md
> docs: unified desc for persist stores in worker & smgr

- venus-worker/Cargo.lock
security alert 9
- 升级 hyper 版本
> chore(deps): upgrade hyper to 0.14.12

- venus-sector-manager/modules/policy/const.go
> fix: preload builtin actors

- venus-sector-manager/cmd/venus-sector-manager/internal/util_miner.go
> fix(vsmgr: cli): malformed output of multiaddr in miner info

- venus-sector-manager/pkg/confmgr/local_mgr.go
> fix(vsmgr: cli): avoid override config files in daemon init

- venus-sector-manager/cmd/venus-sector-manager/internal/util_sealer_snap.go
- venus-sector-manager/core/api.go
- venus-sector-manager/core/client.go
- venus-sector-manager/core/ifaces.go
- venus-sector-manager/core/types.go
- venus-sector-manager/modules/impl/mock/sealer.go
- venus-sector-manager/modules/impl/sectors/snapup_allocator.go
- venus-sector-manager/modules/impl/sectors/snapup_commit.go
- venus-sector-manager/modules/sealer/sealer.go
- venus-sector-manager/modules/sealer/sealer_cli.go
> Chore/dtynn/merge release v0.4.0 nv15

- venus-sector-manager/core/ifaces.go
- venus-sector-manager/modules/impl/commitmgr/commitmgr.go
- venus-sector-manager/modules/impl/sectors/state_mgr.go
- venus-sector-manager/modules/sealer/sealer.go
resolve #178 
- 尝试避免由于本地信息不存在导致无法 terminate 的情况
> feat(vmsgr): init terminated sector state if not exists

- venus-sector-manager/modules/sealer/sealer.go
fix #282 
- 捕获隐藏在 CommitMgr 中的 `state.Load` 返回的 ErrNotFound 类异常
> fix(vsmgr): non-captured state not found error

- docs/zh/12.venus-worker-util.md
- venus-worker-util/Cargo.lock
- venus-worker-util/Cargo.toml
- venus-worker-util/src/bin/venus-worker-util/hwinfo.rs
- venus-worker-util/src/hwinfo/cpu.rs
fix #287 
* hwloc2-rs 新增 get_api_version() 函数 [link](https://github.com/ipfs-force-community/hwloc2-rs/compare/49eff2c2cf7230df79953fef7d08d7de2652b6f9...170ed50de4ce7190d099021e513fb03fb9408999)
* hwinfo 命令会检测 hwloc 版本如果低于 2.0.0 会报错并且不输出 cpu 信息
> fix(worker-util: hwinfo): make sure the hwloc version is at least 2.0.0

- venus-sector-manager/cmd/venus-sector-manager/main.go
- venus-sector-manager/dep/sealer_constructor.go
- venus-sector-manager/go.mod
- venus-sector-manager/go.sum
- venus-sector-manager/pkg/objstore/filestore/store.go
- venus-sector-manager/pkg/objstore/mock_store.go
- venus-sector-manager/ver/ver.go
- 更新 venus-objstore 到 v0.0.3
- 实现最新的 interface
- 日志输出更多信息
> 更新 venus-objstore

- venus-sector-manager/modules/impl/commitmgr/commitmgr.go
…olud try resent
resolve #121 
将 SysErrOutOfGas 对应为 OnChainStateFailed， 以便触发worker 的resent 逻辑
> 处理 SysErrOutOfGas  类的消息

- docs/zh/01.简述.md
- docs/zh/03.venus-worker的配置解析.md
- docs/zh/13.自定义算法和存储方案.md
> 关于自定义方案的支持的概述文档

- venus-worker/src/bin/venus-worker/main.rs
- venus-worker/src/sealing/util.rs
venus-worker 命令的版本字符串从环境变量 GIT_COMMIT 中获取，如果不存在使用 "dev" 代替
> fix(worker): enable to build `venus-worker` without the `GIT_COMMIT` env variable

- docs/zh/09.独立运行的poster节点.md
- venus-sector-manager/cmd/venus-sector-manager/daemon.go
- venus-sector-manager/dep/prover.go
- venus-sector-manager/modules/config_processor.go
- venus-sector-manager/modules/impl/prover/ext/prover.go
- venus-sector-manager/pkg/confmgr/conf_mgr.go
- venus-sector-manager/pkg/extproc/config.go
- venus-sector-manager/pkg/extproc/stage/ext_window_post.go
- venus-sector-manager/pkg/extproc/stage/ext_winning_post.go
- venus-worker/Cargo.lock
- venus-worker/src/bin/venus-worker/processor/mod.rs
- venus-worker/vc-processors/Cargo.toml
- venus-worker/vc-processors/src/builtin/processors.rs
- venus-worker/vc-processors/src/builtin/tasks.rs
- venus-worker/vc-processors/src/fil_proofs/mod.rs
resolve #304
- vc-processors 添加 WinningPost 支持，升级到 v0.1.6
- venus-sector-manager 集成 winning post ext-prover 的支持
> 实现 winning post 外部证明器

- venus-sector-manager/cmd/venus-sector-manager/internal/util_sealer_sectors.go
resolve #298
- 可以按照 miner 进行筛选
- 减少输出内容，引导通过其他命令获取详细信息
> 对扇区列表命令进行调整

- docs/zh/04.venus-sector-manager的配置解析.md
- venus-sector-manager/cmd/venus-sector-manager/internal/util_storage.go
- venus-sector-manager/dep/sealer_constructor.go
- venus-sector-manager/modules/config.go
- venus-sector-manager/modules/sealer/sealer.go
- venus-sector-manager/modules/sealer/sealer_cli.go
- venus-sector-manager/pkg/objstore/mgr.go
- venus-sector-manager/pkg/objstore/mgr_test.go
resolve #289 
- 支持存储分配的黑白名单机制，及相关测试用例
- 改造 `util storage release-serverd` 使用方式
- 文档中添加相关描述
> 支持持久化存储的分配策略：基于矿工号的黑白名单

- CHANGELOG.zh.md
- docs/zh/04.venus-sector-manager的配置解析.md
- venus-sector-manager/modules/config.go
- venus-sector-manager/modules/poster/scheduler.go
- venus-sector-manager/ver/ver.go
- venus-worker/Cargo.lock
- venus-worker/Cargo.toml
resolve #315
- 支持调节 PoSt 相关消息发送策略的可配置项
- v0.3.1 相关
> 支持PoSt 消息策略调节，v0.3.1

- CHANGELOG.zh.md
- docs/zh/04.venus-sector-manager的配置解析.md
- venus-sector-manager/modules/config.go
- venus-sector-manager/modules/poster/scheduler.go
> 引入 v0.3.1 的变动

- venus-sector-manager/core/ifaces.go
- venus-sector-manager/core/types.go
- venus-sector-manager/go.mod
- venus-sector-manager/go.sum
- venus-sector-manager/modules/impl/dealmgr/dealmgr.go
- venus-sector-manager/modules/impl/mock/deal.go
- venus-sector-manager/modules/impl/mock/sealer.go
- venus-sector-manager/modules/sealer/sealer.go
resolve #277
- 更新 venus/venus-shared 到必要版本
- 在 SnapUp 分配过程中进行生命周期约束
> 支持 SnapUp 扇区申请订单时在服务端进行生命周期限制

- docs/en/03.venus-worker-config.md
- docs/zh/03.venus-worker的配置解析.md
fix https://github.com/filecoin-project/venus/issues/5042
03 worker 英文文档
> docs: add venus-cluster en 03 doc

- venus-sector-manager/ver/ver.go
- venus-worker/Cargo.lock
- venus-worker/Cargo.toml
> chore(ver): upgrade to 0.4.0-rc1

- venus-sector-manager/cmd/venus-sector-manager/internal/util_sealer_proving.go
resolve #218 
- 增加 `compact-partitions` 命令
> feat(vsmgr: cli): util sealer proving compact-partitions

- docs/en/06.migrate-sectors-to-venus.md
fix https://github.com/filecoin-project/venus/issues/5082
> docs: add 06 en doc

- .gitignore
- docs/en/03.venus-worker-config.md
fix https://github.com/ipfs-force-community/venus-cluster/issues/335
> docs: update new en cpu.group notes

- docs/zh/04.venus-sector-manager的配置解析.md
- venus-sector-manager/go.mod
- venus-sector-manager/go.sum
- venus-sector-manager/modules/config.go
- venus-sector-manager/modules/impl/commitmgr/commit_processor.go
- venus-sector-manager/modules/impl/commitmgr/commitmgr.go
- venus-sector-manager/modules/impl/commitmgr/precommit_processor.go
- venus-sector-manager/modules/impl/commitmgr/terminate_processor.go
- venus-sector-manager/modules/impl/sectors/snapup_commit.go
- venus-sector-manager/modules/poster/message.go
resolve https://github.com/filecoin-project/venus/issues/4855
支持gasfeecap/maxfee配置
1. 配置文件增加gasfeecap/maxfee/gaspremium/gasoverpremium
2. 发送给messager时候代码feecap和maxfee值
> feat:support gasfeecap and maxfee config

- venus-worker/vc-processors/src/core/ext/consumer.rs
resolve #348 
`span.in_scope` 可以正确的捕获线程外部的 span，使日志输出包含线程外部 span 的内容。
> feat(vc-processors): make the request log include the contents of span outside the thread

- docs/en/10.venus-worker-task-management.md
resolve https://github.com/filecoin-project/venus/issues/5147
> docs: add en doc #10

- docs/en/03.venus-worker-config.md
- docs/zh/03.venus-worker的配置解析.md
- docs/zh/12.venus-worker-util.md
close #334
添加 `processors.{stage_name}.cgroup.cpuset` 配置项的注意事项
> docs(venus-worker): add notes for `processors.{stage_name}.cgroup.cpuset`

- docs/dev/metrics.md
- docs/en/03.venus-worker-config.md
- docs/zh/03.venus-worker的配置解析.md
- venus-worker/Cargo.lock
- venus-worker/Cargo.toml
- venus-worker/assets/venus-worker.mock.toml
- venus-worker/src/config.rs
- venus-worker/src/lib.rs
- venus-worker/src/metrics/mod.rs
- venus-worker/src/metrics/rpc.rs
- venus-worker/src/metrics/task.rs
- venus-worker/src/metrics/util.rs
- venus-worker/src/run.rs
- venus-worker/src/sealing/worker/task/util.rs
resolve #355 
- 实现 metrics / view 的构造宏
- 引入 prometheus exporter
- 在 rpc 调用过程中引入 metrics 操作作为使用范例
> feat(vworker):  metrics basic usages

- venus-worker/src/config.rs
> fix(vw: metrics): use the default config if the metrics config is not set

- .github/workflows/venus-sector-manager.yaml
- .github/workflows/venus-worker-util.yaml
- .github/workflows/venus-worker.yaml
- 激活 dev/coop/* 分支的github actions
> chore(github-actions): enable actions for dev/coop/* branches

- venus-sector-manager/cmd/venus-sector-manager/internal/util_sealer_sectors.go
- venus-sector-manager/core/api.go
- venus-sector-manager/core/client.go
- venus-sector-manager/core/ifaces.go
- venus-sector-manager/core/types.go
- venus-sector-manager/core/types_sector_state.go
- venus-sector-manager/dep/sealer.go
- venus-sector-manager/dep/sealer_constructor.go
- venus-sector-manager/modules/impl/commitmgr/commitmgr.go
- venus-sector-manager/modules/impl/mock/sealer.go
- venus-sector-manager/modules/impl/sectors/rebuild.go
- venus-sector-manager/modules/impl/sectors/rebuild_test.go
- venus-sector-manager/modules/impl/sectors/state_mgr.go
- venus-sector-manager/modules/poster/poster_test.go
- venus-sector-manager/modules/sealer/sealer.go
- venus-sector-manager/modules/sealer/sealer_cli.go
- venus-sector-manager/testutil/testmodules/modules.go
related to #362
- 增加并使用 Rebuild 类型的 SectorWorkerJob
- 实现 SectorSetForRebuild 接口，及相关 CLI
- 实现 RebuildManager ，提供测试用例
> feat(vsmgr): mark sectors as need rebuild

- venus-sector-manager/core/api.go
- venus-sector-manager/core/ifaces.go
- venus-sector-manager/core/types.go
- venus-sector-manager/modules/impl/mock/sealer.go
- venus-sector-manager/modules/impl/sectors/rebuild.go
- venus-sector-manager/modules/impl/sectors/rebuild_test.go
- venus-sector-manager/modules/sealer/sealer.go
- venus-sector-manager/modules/sealer/sealer_cli.go
- venus-worker/Cargo.lock
- venus-worker/Cargo.toml
- venus-worker/src/rpc/sealer/mod.rs
- venus-worker/src/sealing/worker/task/event.rs
- venus-worker/src/sealing/worker/task/sector.rs
#362 
- vsmgr 实现相关接口
- vworker 定义 相关接口和数据结构
> feat: apis & data structs for rebuild planner

- docs/en/11.task-status-flow.md
fix https://github.com/filecoin-project/venus/issues/5174
> docs: add en doc #11

- venus-sector-manager/core/api.go
- venus-sector-manager/modules/impl/mock/sealer.go
- venus-sector-manager/modules/sealer/sealer.go
- venus-worker/src/rpc/sealer/mod.rs
- venus-worker/src/sealing/worker/task/event.rs
- venus-worker/src/sealing/worker/task/planner/common.rs
- venus-worker/src/sealing/worker/task/planner/mod.rs
- venus-worker/src/sealing/worker/task/planner/rebuild.rs
- venus-worker/src/sealing/worker/task/planner/sealer.rs
- venus-worker/src/sealing/worker/task/planner/snapup.rs
- venus-worker/src/sealing/worker/task/sector.rs
> feat(vworker): impl RebuildPlanner

- docs/zh/15.venus-worker_PC1_HugeTLB_Pages_支持.md
完善 `15.venus-worker_PC1_HugeTLB_Pages_支持` 文档
> docs(worker): improve hugetlb pages doc

- .github/pull_request_template.md
involve https://github.com/filecoin-project/venus/issues/4971
change PR template
> chore: unify PR template

- venus-sector-manager/cmd/venus-sector-manager/internal/util_sealer_proving.go
resolve #365 
- 从 lotus 引入 CLI 的 输出改善
> feat(vmsgr: cli): deadline cmds enchantments

- venus-sector-manager/modules/poster/runner.go
> fix(poster): inject right logger

- venus-worker/src/infra/piecestore/proxy.rs
- venus-worker/vc-processors/src/builtin/processors/piece/fetcher/http.rs
#403
修复 piece url 问题
1. 修复把 join 替换为 path_segments_mut().push() 带来的问题
原来的使用 `join` 的代码如下：
```rust
// It's OK.
const ENDPOINT: &str = "/piecestore/";
let h = Url::parse(host).context("parse host")?;
let base = h.join(ENDPOINT).context("build endpoint")?;
```
新的使用 `path_segments_mut().push()` 的代码:
```rust
// Error. "http:/MY_BASE_URL/%2Fpiecestore%2F/" will be generated.
// const ENDPOINT: &str = "/piecestore/";
// It's OK.
const ENDPOINT: &str = "piecestore";
let mut base = Url::parse(host).context("parse host")?;
base.path_segments_mut()
.map_err(|_| anyhow!("url cannot be a base"))?
.push(ENDPOINT);
```
3. 重定向跳转需要用 baseurl join 响应体返回的跳转 location
> fix(worker): fix piece store url

- venus-sector-manager/modules/miner/proof_event.go
> chore(vsm): fix proof event log

- venus-worker/src/sealing/worker/task/planner/common.rs
#362
在重建指定的扇区时， 此扇区的缓存文件夹可能早已经被删除（扇区封装完成会删除临时文件），直接删除它会报文件不存在的错误。 所以仅当文件夹不存在时才删除
> fix(worker): delete the cache folder only if it does not exist

- venus-sector-manager/cmd/venus-sector-manager/internal/util_sealer_sectors.go
fix sector list中match flag和sector的逻辑错误
sealer util
> fix(cli): list sector should work when hit one selectors

- venus-sector-manager/cmd/venus-sector-manager/internal/global.go
- venus-sector-manager/cmd/venus-sector-manager/internal/util_message.go
- venus-sector-manager/modules/impl/commitmgr/commitmgr.go
- venus-sector-manager/modules/impl/sectors/snapup_commit.go
- venus-sector-manager/pkg/messager/api.go
> fix: handle the replace-state of the message

- venus-worker/src/sealing/worker/task/event.rs
related #252
移除过大尺寸的日志
此 pr 需要 cherry pick 到 release/v0.4 分支
> perf(worker): remove some larger log

- venus-sector-manager/cmd/venus-sector-manager/internal/global.go
- venus-sector-manager/cmd/venus-sector-manager/internal/util_message.go
- venus-sector-manager/modules/impl/commitmgr/commitmgr.go
- venus-sector-manager/modules/impl/sectors/snapup_commit.go
- venus-sector-manager/pkg/messager/api.go
> Cherry pick 436

- venus-worker/src/rpc/sealer/mod.rs
- venus-worker/src/sealing/worker/task/event.rs
- venus-worker/src/sealing/worker/task/planner/common.rs
#362
处理扇区重建任务时 `common::pre_commit1` 使用扇区原本的 ticket
> fix(worker: rebuild): pc1 use correct ticket when sector rebuild

- docs/en/11.task-status-flow.md
- docs/zh/11.任务状态流转.md
> docs(worker): add docs for rebuild state flow

- venus-sector-manager/modules/sealer/sealer.go
> fix: inject *SafeConfig Type

- README.md
> docs: remove extra line break

- README.md
> docs: README fix wording

- venus-worker/src/sealing/store/mod.rs
- venus-worker/src/sealing/worker/task/planner/sealer.rs
#362
1. 解决如果同时设置 enable_deals = false 和 disable_cc=true。 disable_cc 无效的问题
2. 启动时输出 sealing_thread 配置到日志中
第1个问题 main 分支应该也存在。 不过影响不大
> fix(worker): disable cc when `enable_deals=false` and `disable_cc=true`

- venus-sector-manager/modules/impl/sectors/tracker.go
> fix(vsmgr): challenge should in a proper range

- docs/en/03.venus-worker-config.md
- docs/zh/03.venus-worker的配置解析.md
related to https://github.com/ipfs-force-community/venus-cluster/issues/362
> docs: en doc for config file hot reload

- venus-sector-manager/modules/poster/poster_test.go
- venus-sector-manager/modules/poster/scheduler.go
- venus-sector-manager/modules/poster/scheduler_test.go
fix #474
更新之后出现频繁的abort， 出现大量context cancel的日志。 按逻辑上来讲只需要revert到在challenge之前的情况下进行重试即可。
> fix(poster): abort should judge on challenge time

- CHANGELOG.zh.md
- venus-sector-manager/ver/ver.go
- venus-worker/Cargo.lock
- venus-worker/Cargo.toml
- 更新 CHANGELOG
- 修改版本号为 v0.5.0-beta1
> Chore/0x5459/release v0.5

- venus-sector-manager/cmd/venus-sector-manager/internal/util_sealer_proving.go
> feat(vsmgr): add a cmd to declare recover-whole-deadline-faults manually

- venus-worker/src/infra/piecestore/mod.rs
- venus-worker/src/run.rs
- venus-worker/src/sealing/worker/task/planner/common.rs
- venus-worker/src/watchdog.rs
fix #501
增加 EmptyPieceStore 使得 GlobalModules 中的 piece_store 不再是 Option 的
> fix(worker): make enable_deals=false work

- venus-worker/src/infra/piecestore/mod.rs
- venus-worker/src/run.rs
- venus-worker/src/sealing/worker/task/planner/common.rs
- venus-worker/src/watchdog.rs
> cherry-pick #502 to v0.5

- venus-worker/src/infra/piecestore/mod.rs
- venus-worker/src/run.rs
- venus-worker/src/sealing/worker/task/planner/common.rs
- venus-worker/src/watchdog.rs
> cherry-pick #502 to v0.4

- CHANGELOG.zh.md
- venus-sector-manager/ver/ver.go
- venus-worker/Cargo.lock
- venus-worker/Cargo.toml
修改版本号为 v0.5.0-beta2
更新 CHANGELOG
> chore(ver): upgrade to 0.5.0-beta2

- CHANGELOG.zh.md
- venus-sector-manager/ver/ver.go
- venus-worker/Cargo.lock
- venus-worker/Cargo.toml
修改版本号为 v0.4.0-rc4
更新 CHANGELOG
> chore(ver): upgrade to 0.4.0-rc4

- venus-sector-manager/modules/impl/commitmgr/commitmgr.go
> fix(vsmgr): handle failed msg in termination

- venus-sector-manager/modules/poster/poster.go
- venus-sector-manager/modules/poster/runner.go
> chore(vsmgr): add log in gen wdpost

- venus-sector-manager/go.mod
- venus-sector-manager/go.sum
依赖的lotus升级到了1.18release，venus升级到了1.8
> feat(vsmgr): keep up with lotus 1.18 & venus 1.8

- venus-sector-manager/modules/impl/sectors/snapup_commit.go
> fix(vsmgr): handle snap up message error code correctly

- CHANGELOG.zh.md
- venus-sector-manager/ver/ver.go
- venus-worker/Cargo.lock
- venus-worker/Cargo.toml
- 更新版本号为 v0.4.0-rc5
- 更新 CHANGELOG
> chore(ver): upgrade to 0.4.0-rc5

- CHANGELOG.zh.md
- venus-sector-manager/ver/ver.go
- venus-worker/Cargo.lock
- venus-worker/Cargo.toml
- 更新版本号为 v0.5.0-beta3
- 更新 CHANGELOG
> chore(ver): upgrade to 0.5.0-beta3

- venus-worker/vc-processors/src/fil_proofs/mod.rs
fix #535 
safe_call 宏保持内部表达式的错误类型
> fix(wdpost): safe_call macro keeps the error type of the inner expr

- venus-worker/vc-processors/src/fil_proofs/mod.rs
> cherry-pick #537 to v0.4

- venus-worker/vc-processors/src/fil_proofs/mod.rs
#537 
cherry-pick #537 to v0.5
> cherry-pick #537 to v0.5

- docs/en/03.venus-worker-config.md
- docs/en/04.venus-sector-manager-config.md
close https://github.com/filecoin-project/venus/issues/5537
#238
> docs: fix typo

- .github/workflows/vc-processors-publish.yaml
- .github/workflows/venus-sector-manager.yaml
- .github/workflows/venus-worker-util.yaml
- .github/workflows/venus-worker.yaml
ref #214
- vsm push 触发构建，主要用于生成缓存
- ci 中读取 rust-toolchain 版本
- 文档修改不触发 ci
> chore(CI): improve ci

- venus-sector-manager/modules/impl/sectors/snapup_commit.go
修改snapup对于消息处理和可重试错误的逻辑，在遇到outofgas或者钱不足等问题时自觉进行重试
> opt(vsmgr): cleanup message id if snap up meet error can retry 

- venus-sector-manager/pkg/kvstore/mongo.go
- venus-sector-manager/pkg/kvstore/mongo_test.go
修复mongodb delete不能正确删除数据库column问题
> fix(vsmgr): fix delete in mongo kv

- venus-sector-manager/modules/impl/sectors/snapup_commit.go
- venus-sector-manager/pkg/kvstore/mongo.go
- venus-sector-manager/pkg/kvstore/mongo_test.go
ref #545 #548
cherry pick #545 #548
> Cherry pick 545 548 to v0.5

- venus-sector-manager/cmd/venus-sector-manager/internal/util_sealer_sectors.go
修改cli list sector中对于不存在laststate的结构的扇区不输出其他信息的bug
> fix(vsmgr): fix cli list sector print last state

- venus-sector-manager/cmd/venus-sector-manager/internal/util_kvstore_migrate.go
- venus-sector-manager/dep/sealer.go
- venus-sector-manager/dep/sealer_constructor.go
- venus-sector-manager/modules/config.go
- venus-sector-manager/modules/impl/sectors/number_allocator_test.go
- venus-sector-manager/modules/impl/sectors/rebuild_test.go
- venus-sector-manager/pkg/kvstore/badger.go
- venus-sector-manager/pkg/kvstore/kv.go
- venus-sector-manager/pkg/kvstore/mongo.go
- venus-sector-manager/pkg/kvstore/mongo_test.go
- venus-sector-manager/pkg/objstore/mgr_test.go
- venus-sector-manager/testutil/testutil.go
ref #561
这个 pr 是 #561 的前置准备工作
- vsm 配置文件新增 `[Common.DB]` 支持配置不同的数据库驱动。
- 新增 DB 接口，为了支持不同的数据库驱动。
```go
type DB interface {
Run(context.Context) error
Close(context.Context) error
// OpenCollection opens a collection with the given name and returns a KVStore,
// creating it if needed.
OpenCollection(name string) (KVStore, error)
}
```
> feat(vsm): add DB interface

- venus-sector-manager/cmd/venus-sector-manager/internal/util_sealer_actor.go
close #559
- sealer actor 所有命令实际使用都要带 `miner`, 故设置为 Required
> opt: miner flag must be set for sealer-actor subcmds

- venus-sector-manager/cmd/venus-sector-manager/internal/util_worker.go
- venus-sector-manager/core/client.go
- venus-sector-manager/core/ifaces.go
- venus-sector-manager/modules/impl/mock/sealer.go
- venus-sector-manager/modules/impl/worker/mgr.go
- venus-sector-manager/modules/sealer/sealer_cli.go
> feat(vsm: cli): add `worker remove` command

- docs/zh/09.独立运行的poster节点.md
> docs: Instructions for the start flags of proxy vsm-node

- docs/zh/05.快速启用.md
- docs/zh/08.snapdeal的支持.md
- venus-sector-manager/cmd/venus-sector-manager/internal/global.go
- venus-sector-manager/cmd/venus-sector-manager/internal/util_sealer_proving.go
- venus-sector-manager/cmd/venus-sector-manager/internal/util_sealer_sectors.go
- venus-sector-manager/cmd/venus-sector-manager/main.go
- venus-sector-manager/dep/sealer_constructor.go
- venus-sector-manager/modules/oldposter/scheduler.go
- venus-sector-manager/modules/policy/const.go
- venus-sector-manager/modules/policy/sealer.go
- venus-sector-manager/modules/poster/runner.go
- venus-sector-manager/modules/sealer/sealer.go
> feat: fetch network params from fullnode

- docs/en/04.venus-sector-manager-config.md
- docs/zh/04.venus-sector-manager的配置解析.md
- venus-sector-manager/dep/sealer_constructor.go
- venus-sector-manager/modules/config.go
- venus-sector-manager/modules/impl/sectors/tracker.go
> docs(vsm):  SectorTracker -> Proving

- venus-worker/vc-processors/Cargo.toml
> chore(worker): upgrade uuid

- venus-sector-manager/dep/sealer_constructor.go
buildSealerCliClient 发生错误时，打印错误
> chore(vsm): log error of `buildSealerCliClient`

- venus-sector-manager/cmd/venus-sector-manager/internal/util_sealer_sectors.go
> fix(vsm: cli:): fix sector number

- venus-sector-manager/Makefile
> chore(make): allow setting Go compiler with `GO`

- venus-sector-manager/modules/poster/runner.go
close #588 
修改submitpost的逻辑，变成做完即发送的模式，方便运维人员监控和处理windowpost过程中的意外
> opt(vsmgr): no wait on submit wdpost stage

- docs/en/04.venus-sector-manager-config.md
- docs/zh/04.venus-sector-manager的配置解析.md
- venus-sector-manager/core/types_result.go
- venus-sector-manager/dep/sealer_constructor.go
- venus-sector-manager/modules/config.go
- venus-sector-manager/modules/impl/prover/prover_prod.go
- venus-sector-manager/modules/impl/sectors/tracker.go
> feat: Configurable pre-check timeouts of sector-tracker

- venus-sector-manager/cmd/venus-sector-manager/internal/run.go
- venus-sector-manager/cmd/venus-sector-manager/internal/util_sealer_proving.go
close #568
- vsm proving check 命令默认只显示成功和失败的扇区数量
- vsm proving check 增加 faulty flag 用于过滤只检查 faulty 扇区（来自[lotus](https://github.com/filecoin-project/lotus/blame/master/cmd/lotus-miner/proving.go#L526-L556), 但是实现方式不同）
> feat(vsm: cli): proving check no longer show detail by default

- venus-worker/src/sealing/worker/task/planner/common.rs
> chore(worker: log): increase log level

- venus-sector-manager/cmd/buildplugin/buildplugin.go
- venus-sector-manager/cmd/venus-sector-manager/daemon.go
- venus-sector-manager/cmd/venus-sector-manager/internal/util.go
- venus-sector-manager/cmd/venus-sector-manager/internal/util_chain.go
- venus-sector-manager/cmd/venus-sector-manager/internal/util_kvstore_migrate.go
- venus-sector-manager/cmd/venus-sector-manager/internal/util_market.go
- venus-sector-manager/cmd/venus-sector-manager/internal/util_message.go
- venus-sector-manager/cmd/venus-sector-manager/internal/util_miner.go
- venus-sector-manager/cmd/venus-sector-manager/internal/util_sealer.go
- venus-sector-manager/cmd/venus-sector-manager/internal/util_sealer_actor.go
- venus-sector-manager/cmd/venus-sector-manager/internal/util_sealer_proving.go
- venus-sector-manager/cmd/venus-sector-manager/internal/util_sealer_sectors.go
- venus-sector-manager/cmd/venus-sector-manager/internal/util_sealer_snap.go
- venus-sector-manager/cmd/venus-sector-manager/internal/util_storage.go
- venus-sector-manager/cmd/venus-sector-manager/internal/util_worker.go
> docs(vsm: cli): improve the usage of cmd

- docs/dev/venus-sector-manager插件框架.md
- venus-sector-manager/cmd/venus-sector-manager/daemon.go
- venus-sector-manager/cmd/venus-sector-manager/mock.go
- venus-sector-manager/cmd/venus-sector-manager/server.go
- venus-sector-manager/go.mod
- venus-sector-manager/go.sum
- vsm-plugin/examples/memdb/go.mod
- vsm-plugin/examples/memdb/go.sum
- vsm-plugin/spi.go
close #595
新增 RegisterJsonRpc 类型插件，允许注册自定义的 jsonrpc 接口
> feat(vsm: plugin): support register jsonrpc

- docs/en/03.venus-worker-config.md
- docs/zh/03.venus-worker的配置解析.md
> docs(vw): describe the `sealing_thread`

- docs/en/03.venus-worker-config.md
- docs/zh/03.venus-worker的配置解析.md
- venus-worker/Cargo.lock
- venus-worker/src/sealing/processor/external/config.rs
- venus-worker/src/sealing/processor/external/sub/mod.rs
- venus-worker/vc-processors/Cargo.toml
- venus-worker/vc-processors/examples/builtin-proc.rs
- venus-worker/vc-processors/examples/customize-proc.rs
- venus-worker/vc-processors/examples/sqr-producer.rs
- venus-worker/vc-processors/src/core/ext/producer.rs
close #604
小重构外部执行器逻辑
- 子进程意外退出后，将错误抛出到 venus-worker。
- 外部执行器新增 `auto_restart` 配置，在外部执行器子进程意外退出后自动重启外部执行器子进程。
> fix(worker): handle defunct child process

- venus-worker/src/config.rs
- venus-worker/src/run.rs
- venus-worker/vc-processors/src/core/ext/consumer.rs
ref #606
toml 格式渲染 map 时，必须将 map 字段放到配置的最后，否则会报 ValueAfterTable 的错误。
> fix(worker): render setup config

- venus-sector-manager/cmd/venus-sector-manager/internal/global.go
- venus-sector-manager/cmd/venus-sector-manager/main.go
ref #616
Cherry pick #616 to release/v0.5
> Cherry pick #616 to release/v0.5

- CHANGELOG.zh.md
- venus-sector-manager/ver/ver.go
- venus-worker/Cargo.lock
- venus-worker/Cargo.toml
close #581
发布 v0.5.1-rc1 版本支持 nv18
> chore: release v0.5.1-rc1

- venus-sector-manager/modules/config_util.go
MarshalText 没有错误的情况下不应该返回 nil， 否则新版的 toml 库会报错导致无法启动
> fix(vsm): `MarshalText` should not return nil and no error

- venus-sector-manager/cmd/venus-sector-manager/internal/global.go
- venus-sector-manager/cmd/venus-sector-manager/main.go
ref #616
Cherry pick #616 to release/v0.5
> Cherry pick #616 to release/v0.4

- venus-sector-manager/modules/config_util.go
ref #619
Cherry-pick #619 to release/v0.4
> Cherry-pick #619 to release/v0.4

- CHANGELOG.zh.md
- venus-sector-manager/ver/ver.go
- venus-worker/Cargo.lock
- venus-worker/Cargo.toml
ref #581
发布 v0.4.1-rc1 版本支持 nv18
> chore: release v0.4.1-rc1

- venus-sector-manager/go.mod
- venus-sector-manager/go.sum
> fix(vsm): upgrade jsonrpc to fix panic

- venus-sector-manager/go.mod
- venus-sector-manager/go.sum
ref #623
Cherry pick #623 to release/v0.5
> Cherry pick #623 to release/v0.5

- venus-sector-manager/go.mod
- venus-sector-manager/go.sum
ref #623
Cherry pick #623 to release/v0.4
> Cherry pick #623 to release/v0.4

- CHANGELOG.zh.md
- venus-sector-manager/ver/ver.go
- venus-worker/Cargo.lock
- venus-worker/Cargo.toml
ref #581
发布 v0.4.1-rc2 版本修复 jsonrpc bug
> chore: release v0.5.1-rc2

- CHANGELOG.zh.md
- venus-sector-manager/ver/ver.go
- venus-worker/Cargo.lock
- venus-worker/Cargo.toml
ref #581
发布 v0.4.1-rc2 版本修复 jsonrpc bug
> chore: release v0.4.1-rc2

- venus-sector-manager/cmd/plugin/internal/checkdep.go
调用 `SetRequire` 方法修改 mod file 的内容
> fix(vsm: cli): call `SetRequire` to actually change the mod file

- venus-sector-manager/modules/impl/commitmgr/commit_processor.go
> fix: generate AggregateSeal verify info

- venus-sector-manager/cmd/venus-sector-manager/internal/util_market.go
- venus-sector-manager/go.mod
- venus-sector-manager/go.sum
- venus-sector-manager/modules/impl/dealmgr/dealmgr.go
- venus-sector-manager/pkg/market/api.go
- venus-sector-manager/pkg/piecestore/proxy_test.go
> feat: refactor updatedealstatus api

- venus-sector-manager/cmd/venus-sector-manager/internal/util_market.go
- venus-sector-manager/go.mod
- venus-sector-manager/go.sum
- venus-sector-manager/modules/impl/dealmgr/dealmgr.go
- venus-sector-manager/pkg/chain/blockstore.go
- venus-sector-manager/pkg/market/api.go
- venus-sector-manager/pkg/piecestore/proxy_test.go
ref #640
Cherry pick #640 to release/v0.5
> Cherry-pick #640 to `release/v0.5`

- venus-sector-manager/cmd/venus-sector-manager/internal/util_market.go
- venus-sector-manager/go.mod
- venus-sector-manager/go.sum
- venus-sector-manager/modules/impl/dealmgr/dealmgr.go
- venus-sector-manager/pkg/chain/blockstore.go
- venus-sector-manager/pkg/market/api.go
- venus-sector-manager/pkg/piecestore/proxy_test.go
ref #640
Cherry-pick #640 to release/v0.4
> Cherry-pick #640 to release/v0.4

- CHANGELOG.zh.md
- venus-sector-manager/go.mod
- venus-sector-manager/go.sum
- venus-sector-manager/ver/ver.go
- venus-worker/Cargo.lock
- venus-worker/Cargo.toml
ref #635
- 升级 lotus 到 v1.20.0
- 发布 v0.5.1 正式版本，兼容 nv18
> release v0.5.1

- docs/zh/05.快速启用.md
> docs: update link

- CHANGELOG.zh.md
- venus-sector-manager/modules/impl/commitmgr/commit_processor.go
- venus-sector-manager/ver/ver.go
- venus-worker/Cargo.lock
- venus-worker/Cargo.toml
ref #638
Cherry-pick #638 to release/v0.4
Release v0.4.2
> Chore/0x5459/release v0.4.2

- CHANGELOG.zh.md
- venus-sector-manager/modules/impl/commitmgr/commit_processor.go
- venus-sector-manager/ver/ver.go
- venus-worker/Cargo.lock
- venus-worker/Cargo.toml
ref #638
- Cherry-pick #638 to release/v0.5
- Release v0.5.2
> Chore/0x5459/release v0.5.2

- venus-worker/src/infra/piecestore/local.rs
> chore(worker): log piece path

- venus-sector-manager/cmd/venus-sector-manager/internal/util_sealer_proving.go
- venus-sector-manager/cmd/venus-sector-manager/internal/util_sealer_sectors.go
- venus-sector-manager/core/api.go
- venus-sector-manager/core/client.go
- venus-sector-manager/core/ifaces.go
- venus-sector-manager/dep/sealer_constructor.go
- venus-sector-manager/modules/impl/mock/sealer.go
- venus-sector-manager/modules/impl/sectors/tracker.go
- venus-sector-manager/modules/oldposter/scheduler.go
- venus-sector-manager/modules/poster/runner.go
- venus-sector-manager/modules/sealer/sealer.go
- venus-sector-manager/modules/sealer/sealer_cli.go
fix #656 
- proving check 加标志 `--state-check` 检查本地存储扇区状态：主要是检查 `SealedCID`；
- 添加 sectors finalize 命令：手动终结已经上链的扇区，更新状态为`完成`；
> feat: add sector finalize cmd

- docs/en/11.task-status-flow.md
- docs/zh/11.任务状态流转.md
- venus-sector-manager/cmd/venus-sector-manager/internal/util_sealer_sectors.go
禁用 `util sealer sectors abort` 命令
> fix(vsm): disable sectors_abort command

- venus-worker/src/util/net.rs
> feat(worker): support dns for rpc mutiladdr

- venus-worker/src/bin/venus-worker/main.rs
- venus-worker/src/lib.rs
- venus-worker/src/util/mod.rs
- venus-worker/src/util/panic_hook.rs
> feat(worker): set_panic_hook: exit the process when panic.

- docs/zh/13.自定义算法和存储方案.md
> docs(13): vsm plugin

- CHANGELOG.zh.md
- venus-sector-manager/ver/ver.go
- venus-worker/Cargo.lock
- venus-worker/Cargo.toml
增加 v0.6.0-rc1 changelog
升级 venus-cluster 版本号: v0.5 -> v0.6.0-rc1
> chore: release v0.6.0-rc1

- venus-worker/Cargo.lock
- venus-worker/Cargo.toml
- venus-worker/vc-processors/Cargo.toml
升级 `rust-fil-proofs` 库到 v14.0.0
> chore(worker): upgrade `rust-fil-proofs` to v14.0.0

- venus-worker/src/run.rs
- venus-worker/src/util/net.rs
修复当worker中配置 vsm rpc地址时填入域名时无法正确解析的问题
> fix(worker): correctly parsing URLs with hostnames

- venus-worker/src/run.rs
- venus-worker/src/util/net.rs
#691
Cherry pick #691 to release/v0.6
> Cherry pick #691 to release/v0.6

- venus-sector-manager/go.mod
- venus-sector-manager/go.sum
- venus-sector-manager/modules/config.go
- venus-sector-manager/modules/impl/commitmgr/policy.go
- venus-sector-manager/modules/policy/sealer.go
> Cherry pick #695 to release/v0.6

- venus-sector-manager/go.mod
- venus-sector-manager/go.sum
- venus-sector-manager/modules/config.go
- venus-sector-manager/modules/impl/commitmgr/policy.go
- venus-sector-manager/modules/policy/sealer.go
撤销 PR #686
ref https://github.com/filecoin-project/lotus/commit/68ed494a6e497ac556eb93b28b2536c881dc9a4c
> feat(vsm): revert fip 0052

- venus-sector-manager/go.mod
- venus-sector-manager/go.sum
- venus-sector-manager/modules/config.go
- venus-sector-manager/modules/impl/commitmgr/policy.go
- venus-sector-manager/modules/policy/sealer.go
> Cherry pick #695 to release/v0.5

- CHANGELOG.zh.md
- venus-sector-manager/ver/ver.go
- venus-worker/Cargo.lock
- venus-worker/Cargo.toml
> chore(*): release v0.6.0-rc2

- CHANGELOG.zh.md
- venus-sector-manager/ver/ver.go
- venus-worker/Cargo.lock
- venus-worker/Cargo.toml
> chore(*): release v0.5.3-rc1

- CHANGELOG.zh.md
> docs: update changelog

- venus-sector-manager/pkg/extproc/stage/ext_window_post.go
兼容 rust-filecoin-proofs-api api-version
> fix(vsm): compatible with rust-filecoin-proofs-api

- CHANGELOG.zh.md
- venus-sector-manager/pkg/extproc/stage/ext_window_post.go
- venus-sector-manager/ver/ver.go
- venus-worker/Cargo.lock
- venus-worker/Cargo.toml
#702
Cherry pick #702 to release/v0.6
> Cherry pick #702 to release/v0.6

- CHANGELOG.zh.md
- venus-sector-manager/pkg/extproc/stage/ext_window_post.go
- venus-sector-manager/ver/ver.go
- venus-worker/Cargo.lock
- venus-worker/Cargo.toml
#702
Cherry pick #702 to release/v0.5
> Cherry pick #702 to release/v0.5

- venus-sector-manager/modules/poster/runner.go
> chore(vsm): fix log: mid -> message-id

- venus-sector-manager/go.mod
- venus-sector-manager/go.sum
升级 vsm 依赖库
- go-state-types v0.11.0-rc1 -> v0.11.0-rc2
- lotus v1.22.0 -> v1.22.1
- venus v1.11.0 -> v1.11.1
- filecoin-ffi v1.22.1
> chore(vsm): update deps

- CHANGELOG.zh.md
- venus-sector-manager/go.mod
- venus-sector-manager/go.sum
- venus-sector-manager/ver/ver.go
- venus-worker/Cargo.lock
- venus-worker/Cargo.toml
#710
- Cherry pick #710 to release/v0.6
- Release v0.6.0
> Cherry pick #710 to release/v0.6 & Release v0.6.0

- CHANGELOG.zh.md
- venus-sector-manager/go.mod
- venus-sector-manager/go.sum
- venus-sector-manager/ver/ver.go
- venus-worker/Cargo.lock
- venus-worker/Cargo.toml
#710
- Cherry pick #710 to release/v0.5
- Release v0.5.3
> Cherry pick #710 to release/v0.5 & Release v0.5.3

- docs/en/03.venus-worker-config.md
- docs/zh/03.venus-worker的配置解析.md
- venus-worker/src/config.rs
- venus-worker/src/infra/piecestore/local.rs
- venus-worker/src/run.rs
close #713
venus-worker local_pieces_dirs 支持配置多个目录
> feat(worker): support multiple dirs for local_pieces_dirs

- CHANGELOG.zh.md
> docs(changelog): fix typo

- venus-sector-manager/pkg/logging/log.go
> feat(vsm): set default log level to `INFO`

- venus-worker/Cargo.lock
- venus-worker/Cargo.toml
- venus-worker/Makefile
- venus-worker/src/bin/venus-worker/generator/mod.rs
- venus-worker/src/bin/venus-worker/main.rs
- venus-worker/src/bin/venus-worker/processor/mod.rs
- venus-worker/src/bin/venus-worker/store.rs
- venus-worker/src/bin/venus-worker/worker/mod.rs
- venus-worker/src/lib.rs
- venus-worker/src/logging/mod.rs
- venus-worker/src/run.rs
- venus-worker/src/sealing/util.rs
- venus-worker/src/version.rs
close #666
- 升级 clap v4
- 使用 clap derive mode
> feat(worker): clap derive mode

- venus-worker/src/sealing/config.rs
- venus-worker/src/sealing/sealing_thread/mod.rs
> feat(worker): make hot config file optional

- venus-sector-manager/modules/impl/commitmgr/commitmgr.go
提交消息时遇到 ErrInsufficientFunds 错误时重试
> fix(vsm): handle ErrInsufficientFunds

- venus-sector-manager/modules/impl/commitmgr/commitmgr.go
ref #725
Cherry pick #725 to release/v0.6
> Cherry pick #725 to release/v0.6

- venus-sector-manager/modules/impl/sectors/snapup_commit.go
close #494
检查升级扇区是否在不在锁定窗口之内
参考:
https://github.com/filecoin-project/builtin-actors/blob/10f547c950a99a07231c08a3c6f4f76ff0080a7c/actors/miner/src/lib.rs#L1113-L1124
https://github.com/filecoin-project/lotus/blob/9321e0fd1404a479d4dee2f1e13d5ea5fbe7ef4e/storage/pipeline/states_replica_update.go#L106-L110
> feat(vsm): check if the update sector deadline is mutable

- venus-sector-manager/go.mod
- venus-sector-manager/go.sum
- venus-sector-manager/modules/impl/sectors/indexer.go
- venus-sector-manager/modules/impl/sectors/number_allocator.go
- venus-sector-manager/modules/impl/sectors/number_allocator_test.go
- venus-sector-manager/modules/impl/sectors/rebuild.go
- venus-sector-manager/modules/impl/sectors/rebuild_test.go
- venus-sector-manager/modules/impl/sectors/snapup_allocator.go
- venus-sector-manager/modules/impl/sectors/state_mgr.go
- venus-sector-manager/modules/impl/worker/mgr.go
- venus-sector-manager/pkg/kvstore/badger.go
- venus-sector-manager/pkg/kvstore/badger_test.go
- venus-sector-manager/pkg/kvstore/kvstore.go
- venus-sector-manager/pkg/kvstore/mongo.go
- venus-sector-manager/pkg/kvstore/mongo_test.go
- venus-sector-manager/pkg/kvstore/prefix_wrapper.go
- venus-sector-manager/pkg/objstore/mgr.go
- venus-sector-manager/pkg/objstore/mgr_test.go
- venus-sector-manager/testutil/testutil.go
- vsm-plugin/examples/memdb/go.mod
- vsm-plugin/examples/memdb/go.sum
- vsm-plugin/examples/memdb/memdb.go
- vsm-plugin/examples/memdb/memdb_test.go
- vsm-plugin/kvstore/kv.go
> feat(vsm): support transaction for kvstore

- venus-sector-manager/cmd/venus-sector-manager/internal/util_sealer_sectors.go
- venus-sector-manager/core/types_specs_actors.go
> fix(vsm): call new method `ExpirationExtension2` to extend sector

- venus-sector-manager/cmd/venus-sector-manager/internal/global.go
> feat(vsm): read the location of data directory from env vars

- venus-sector-manager/cmd/venus-sector-manager/internal/util_sealer_actor.go
- 移除地址使用方式的颜色，加颜色的文字会影响 text/tabwriter 的排版
- 修复地址使用方式判断方式
> fix(vsm): remove text color

- CHANGELOG.zh.md
- venus-sector-manager/cmd/venus-sector-manager/internal/global.go
- venus-sector-manager/cmd/venus-sector-manager/internal/util_sealer_sectors.go
- venus-sector-manager/core/types_specs_actors.go
- venus-sector-manager/modules/impl/sectors/snapup_commit.go
- venus-sector-manager/pkg/logging/log.go
- venus-sector-manager/ver/ver.go
- venus-worker/Cargo.lock
- venus-worker/Cargo.toml
#719 #730 #732 #733 
- Cherry-pick pr 
- #719 
- #730 
- #732 
- #733 
- Release v0.6.1
> Cherry pick pr #719 #730 #732 #733 to release v0.6

- venus-sector-manager/modules/policy/const.go
- venus-sector-manager/modules/sealer/sealer.go
- venus-sector-manager/pkg/objstore/mgr.go
> chore(vsm): change logging level: debug -> info

- CHANGELOG.zh.md
- venus-sector-manager/cmd/venus-sector-manager/internal/util_market.go
- venus-sector-manager/go.mod
- venus-sector-manager/modules/impl/dealmgr/dealmgr.go
- venus-sector-manager/modules/policy/const.go
- venus-sector-manager/modules/sealer/sealer.go
- venus-sector-manager/pkg/objstore/mgr.go
- venus-sector-manager/ver/ver.go
- venus-worker/Cargo.lock
- venus-worker/Cargo.toml
#681 #738
Cherry pick #681 #738 to release/v0.6
> Cherry pick pr #681 #738 to release v0.6

- venus-sector-manager/modules/impl/commitmgr/commitmgr.go
遇到 BadCommD 等错误，不再直接 abort 扇区并释放订单，而是让 venus-worker 暂停当前线程，等待人工介入处理。
不直接将 venus-market 的数据库中的订单状态改为错误状态是因为一个扇区中可能不止一个订单。
> fix(vsm): `BadCommD` error no longer abort the sector

- venus-sector-manager/modules/impl/commitmgr/commitmgr.go
#742
Cherry pick #742 to release/v0.6
> Cherry pick #742 to release/v0.6

- venus-sector-manager/modules/impl/commitmgr/commitmgr.go
close #745
提交 precommit 消息时，消息执行失败不再 abort 扇区，而是返回永久错误
> fix(vsm): message exec failure no longer abort sector

- Dockerfile.vsm
- Makefile
- venus-worker/Dockerfile
更新 vsm dockerfile，正确安装 opencl 驱动
> feat(docker): update dockerfile

- CHANGELOG.zh.md
- Dockerfile.vsm
- Makefile
- venus-sector-manager/ver/ver.go
- venus-worker/Cargo.lock
- venus-worker/Cargo.toml
- venus-worker/Dockerfile
#750
- Cherry pick #750 to release/v0.6
- Release v0.6.4
> Cherry pick #750 to release/v0.6

- Dockerfile.vsm
- venus-worker/Dockerfile
> fix(docker): install tzdata

- venus-worker/Cargo.toml
- venus-worker/src/logging/mod.rs
> fix(worker):  obtain the local timezone correctly

- venus-sector-manager/modules/poster/runner.go
wdpost 消息成功上链会打印类似下面的日志
```
window post message succeeded: xxx
```
`xxx` 是消息签名后的 id
> feat(vsm): make wdpost logs more detailed

- CHANGELOG.zh.md
- Dockerfile.vsm
- venus-sector-manager/modules/impl/sectors/snapup_commit.go
- venus-sector-manager/modules/poster/runner.go
- venus-sector-manager/ver/ver.go
- venus-worker/Cargo.lock
- venus-worker/Cargo.toml
- venus-worker/Dockerfile
#752 #755 #756
- Cherry pick #752 #755 #756 to release/v0.6
- Release v0.6.5
> Cherry pick #752 #755 #756 to release/v0.6

- venus-sector-manager/modules/poster/runner.go
> fix(vsm): wdpost panic

- venus-sector-manager/modules/poster/runner.go
#759
Cherry pick #759 to release/v0.6
> Cherry pick #759 to release v0.6

- venus-sector-manager/cmd/venus-sector-manager/internal/util_worker.go
- venus-sector-manager/core/api.go
- venus-sector-manager/core/client.go
- venus-sector-manager/core/worker.go
- venus-sector-manager/modules/impl/mock/sealer.go
- venus-sector-manager/modules/sealer/sealer_cli.go
- venus-worker/src/config.rs
- venus-worker/src/rpc/sealer/mod.rs
- venus-worker/src/rpc/worker/mod.rs
- venus-worker/src/sealing/ping.rs
- venus-worker/src/sealing/service.rs
close #717
- vsm 新增 version 接口
- vsm cli `worker list` 添加 version 列
- venus-worker 新增 version 接口
> *: add API to get version

- venus-worker/src/metadb/mod.rs
- venus-worker/src/sealing/config.rs
- venus-worker/src/sealing/sealing_thread/mod.rs
- venus-worker/src/sealing/sealing_thread/task/mod.rs
- venus-worker/src/sealing/sealing_thread/task/sector.rs
> fix(worker): safely modify the sealing thread plan

- damocles-worker/src/bin/damocles-worker/store.rs
兼容老版本的 cli
arg 上加上 `num_args=1..` 参数，命令  `damocles-worker store sealing-init -l s0 s1 s2` 就可以正常执行，否则需要 `damocles-worker store sealing-init -l s0 -l s1 -l s2`。
另外不加上 `num_args=1..` 参数，允许输入空参数。
> fix(worker): compatible with legacy cli

- damocles-manager/cmd/damocles-manager/internal/util_sealer_proving.go
> fix(manager): typo

- damocles-manager/cmd/damocles-manager/internal/util_sealer_sectors.go
- damocles-manager/core/api.go
- damocles-manager/core/client.go
- damocles-manager/modules/impl/mock/sealer.go
- damocles-manager/modules/sealer/sealer.go
- damocles-manager/modules/sealer/sealer_cli.go
> feat: find sector in all states

- CHANGELOG.zh.md
- damocles-manager/ver/ver.go
- damocles-worker/Cargo.lock
- damocles-worker/Cargo.toml
> chore: release v0.7.0-rc1

- damocles-manager/cmd/damocles-manager/internal/global_test.go
- damocles-manager/modules/sealer/sealer.go
> fix: handle nil pci

- .github/dependabot.yml
Configures dependabot to auto-update actions in the future. Related to https://filecoinproject.slack.com/archives/C03KLC57LKB/p1686680229440949
> chore: update github actions

- damocles-manager/modules/impl/sectors/snapup_commit.go
- damocles-manager/modules/impl/sectors/snapup_commit_test.go
修复 snapdeal 判断目标扇区是否为时空证明锁定期的 bug
> fix: check deadline is mutable

- damocles-manager/modules/config.go
- damocles-manager/modules/impl/sectors/snapup_commit.go
- docs/en/04.damocles-manager-config.md
- docs/zh/04.damocles-manager的配置解析.md
> feat: skip cleanup CC data

- CHANGELOG.zh.md
- docs/en/04.venus-sector-manager-config.md
- docs/zh/04.venus-sector-manager的配置解析.md
- venus-sector-manager/modules/config.go
- venus-sector-manager/modules/impl/sectors/snapup_commit.go
- venus-sector-manager/modules/impl/sectors/snapup_commit_test.go
- venus-sector-manager/ver/ver.go
- venus-worker/Cargo.lock
- venus-worker/Cargo.toml
- Cherry-pick #789 #790 to release/v0.6
- Release v0.6.6
> Cherry pick pr #789 #790 to release v0.6

- CHANGELOG.zh.md
- README.md
- damocles-manager/ver/ver.go
- damocles-worker/Cargo.lock
- damocles-worker/Cargo.toml
> chore: release v0.7.0-rc2

- .github/dependabot.yml
- .github/workflows/damocles-manager.yaml
- .github/workflows/damocles-worker-util.yaml
- .github/workflows/damocles-worker.yaml
- .github/workflows/docker.yaml
- .github/workflows/vc-processors-publish.yaml
- CHANGELOG.zh.md
- README.md
- damocles-manager/cmd/damocles-manager/internal/global_test.go
- damocles-manager/core/types.go
- damocles-manager/modules/config.go
- damocles-manager/modules/impl/sectors/snapup_commit.go
- damocles-manager/modules/impl/sectors/snapup_commit_test.go
- damocles-manager/modules/impl/sectors/unseal.go
- damocles-manager/modules/impl/sectors/unseal_test.go
- damocles-manager/modules/sealer/sealer.go
- damocles-manager/ver/ver.go
- damocles-worker/Cargo.lock
- damocles-worker/Cargo.toml
- docs/en/04.damocles-manager-config.md
- docs/zh/04.damocles-manager的配置解析.md
- docs/zh/15.damocles-worker_PC1_HugeTLB_Pages_支持.md
> Release v0.7.0-rc2

- damocles-manager/dep/gateway.go
ref: https://github.com/ipfs-force-community/damocles/issues/793
> fix: build market event client without market addr configured

- CHANGELOG.zh.md
- damocles-manager/ver/ver.go
- damocles-worker/Cargo.lock
- damocles-worker/Cargo.toml
> chore: bump version to v0.7.0-rc3

- damocles-manager/go.mod
- damocles-manager/modules/impl/prover/worker/task_mgr.go
- damocles-manager/modules/impl/prover/worker/task_mgr_kv.go
- damocles-manager/modules/impl/sectors/state_mgr.go
- damocles-manager/pkg/kvstore/kvstore.go
ref #723
新增用于管理 windowPoSt 任务的 TaskManager
> feat: add wdpost task manager

- CHANGELOG.zh.md
- damocles-manager/go.mod
- damocles-manager/go.sum
- damocles-manager/ver/ver.go
- damocles-worker/Cargo.lock
- damocles-worker/Cargo.toml
> chore: release v0.7.0

- damocles-worker/Cargo.toml
- damocles-worker/src/bin/damocles-worker/processor/mod.rs
> fix(worker): pc1 load hugepage files from env

- CHANGELOG.zh.md
- damocles-manager/ver/ver.go
- damocles-worker/Cargo.lock
- damocles-worker/Cargo.toml
- damocles-worker/src/bin/damocles-worker/processor/mod.rs
> Chore/0x5459/release v0.7.1

- damocles-manager/modules/impl/mock/sealer.go
- damocles-manager/modules/sealer/sealer.go
> fix: check if array is null

- damocles-manager/modules/impl/mock/sealer.go
- damocles-manager/modules/sealer/sealer.go
cherry-pick #807 to release/v0.7
> cherry-pick #807 to release/v0.7

- damocles-manager/go.mod
- damocles-worker/src/config.rs
- damocles-worker/src/rpc/sealer/mod.rs
- damocles-worker/src/run.rs
- damocles-worker/src/sealing/processor/mod.rs
- damocles-worker/src/sealing/sealing_thread/task/event.rs
- damocles-worker/src/sealing/sealing_thread/task/planner/mod.rs
- damocles-worker/src/sealing/sealing_thread/task/planner/wdpost.rs
- damocles-worker/src/sealing/sealing_thread/task/sector.rs
- damocles-worker/src/watchdog.rs
ref: https://github.com/ipfs-force-community/venus-cluster/issues/724
> feat: add wdpost planner

- damocles-worker/src/bin/damocles-worker/main.rs
- damocles-worker/src/bin/damocles-worker/worker/mod.rs
- damocles-worker/src/client.rs
- damocles-worker/src/config.rs
- damocles-worker/src/lib.rs
- docs/en/10.damocles-worker-task-management.md
- docs/en/11.task-status-flow.md
- docs/zh/10.venus-worker任务管理.md
- docs/zh/11.任务状态流转.md
- docs/zh/16.扇区重建的支持.md
> feat(cli): load host from flag

- damocles-manager/cmd/damocles-manager/internal/util_worker.go
- damocles-manager/go.mod
> feat: add cli to manager wdpost task

- damocles-worker/Cargo.lock
- damocles-worker/Cargo.toml
- damocles-worker/vc-processors/Cargo.toml
- damocles-worker/vc-processors/src/sys/cgroup.rs
> fix: compatible with cgroup v2

- damocles-manager/cmd/damocles-manager/internal/util_worker.go
- damocles-manager/core/types_wdpost.go
- damocles-manager/dep/sealer.go
- damocles-manager/dep/sealer_constructor.go
- damocles-manager/modules/impl/prover/worker/prover.go
- damocles-manager/modules/impl/prover/worker/task_mgr_kv.go
- damocles-manager/modules/impl/sectors/proving.go
> feat(cli: wdpost: list): show deadline

- damocles-manager/cmd/damocles-manager/internal/util_worker.go
- damocles-manager/core/api.go
- damocles-manager/core/client_gen.go
- damocles-manager/core/types_wdpost.go
- damocles-manager/core/worker.go
- damocles-manager/dep/prover.go
- damocles-manager/dep/sealer_constructor.go
- damocles-manager/modules/impl/prover/worker/config.go
- damocles-manager/modules/impl/prover/worker/prover.go
- damocles-manager/modules/impl/prover/worker/rpc.go
- damocles-manager/modules/impl/prover/worker/task_mgr_kv.go
- damocles-manager/pkg/kvstore/kvstore.go
- damocles-manager/pkg/logging/log.go
ref #723
- improve wdpost cli
- fix some bugs related to wdpost
> feat(cli: wdpost): improve cli

- damocles-manager/cmd/damocles-manager/internal/util_sealer_sectors.go
- docs/zh/11.任务状态流转.md
- docs/zh/18.Unseal任务的支持.md
close https://github.com/ipfs-force-community/damocles/issues/820
close https://github.com/ipfs-force-community/damocles/issues/776
> feat: modify cli to unseal piece from unseal file

- damocles-worker/src/bin/damocles-worker/main.rs
- damocles-worker/src/lib.rs
- damocles-worker/src/util/panic_hook.rs
- damocles-worker/vc-processors/src/fil_proofs/mod.rs
> fix(worker): `safe_call` disable panic hook

- CHANGELOG.zh.md
- damocles-manager/ver/ver.go
- damocles-worker/Cargo.lock
- damocles-worker/Cargo.toml
- damocles-worker/src/bin/damocles-worker/main.rs
- damocles-worker/src/lib.rs
- damocles-worker/src/util/panic_hook.rs
- damocles-worker/vc-processors/src/fil_proofs/mod.rs
ref #834
1. Cherry pick pr #834 to release v0.7
2. Release v0.7.2
> Cherry pick pr #834 to release v0.7

- docs/zh/05.快速启用.md
> 添加miner create 返回值的解释

- damocles-manager/cmd/damocles-manager/internal/util_sealer_sectors.go
- damocles-manager/dep/gateway.go
- damocles-manager/dep/sealer_constructor.go
- damocles-manager/modules/impl/sectors/unseal.go
- damocles-manager/modules/impl/sectors/unseal_test.go
- damocles-worker/src/sealing/sealing_thread/task/event.rs
- damocles-worker/src/sealing/sealing_thread/task/planner/unseal.rs
- damocles-worker/src/sealing/sealing_thread/task/sector.rs
- docs/zh/11.任务状态流转.md
close https://github.com/ipfs-force-community/damocles/issues/832
- 修复使用未经解释的 market address 的问题
- 去除 unseal 准备过程中的文件传输
> fix: use market addr from extration only / 只使用解释之后的 market addr 

- docs/zh/06.导入已存在的扇区数据.md
> attach proving check

- CHANGELOG.zh.md
- damocles-manager/ver/ver.go
- damocles-worker/Cargo.lock
- damocles-worker/Cargo.toml
> chore: release v0.8.0-rc1

- damocles-manager/core/types_wdpost.go
wdpost worker-prover cli 修复无法显示 minerID 的 bug。
> fix(worker): show miner-id

- docs/zh/09.独立运行的poster节点.md
> docs(09): update

- damocles-manager/cmd/damocles-manager/internal/util_sealer_sectors.go
> fix: check flag really do it

- CHANGELOG.zh.md
- damocles-manager/cmd/damocles-manager/internal/util_sealer_sectors.go
- damocles-manager/ver/ver.go
- damocles-worker/Cargo.lock
- damocles-worker/Cargo.toml
- Cherry pick pr #853 #854 to release/v0.8
- Release v0.8.0-rc3
> Cherry pick pr #853 #854 to release/v0.8

- damocles-manager/cmd/damocles-manager/internal/util_sealer_sectors.go
> fix(manager: cli): Damocles -> Sealer

- damocles-manager/cmd/damocles-manager/internal/util_sealer_proving.go
- damocles-manager/cmd/damocles-manager/internal/util_worker.go
- damocles-manager/core/api.go
- damocles-manager/core/client_gen.go
- damocles-manager/core/prover.go
- damocles-manager/core/types_wdpost.go
- damocles-manager/modules/impl/prover/ext/prover.go
- damocles-manager/modules/impl/prover/prover_fake.go
- damocles-manager/modules/impl/prover/prover_prod.go
- damocles-manager/modules/impl/prover/worker/job_mgr_kv.go
- damocles-manager/modules/impl/prover/worker/prover.go
- damocles-manager/modules/impl/prover/worker/rpc.go
- damocles-manager/modules/poster/runner.go
- damocles-manager/modules/sealer/sealer_cli.go
- damocles-manager/pkg/slices/map.go
- damocles-manager/pkg/strings/join.go
- damocles-manager/pkg/strings/join_test.go
- damocles-manager/ver/ver.go
- damocles-worker/Cargo.lock
- damocles-worker/Cargo.toml
- docs/zh/09.独立运行的poster节点.md
- Cherry pick pr #858 to release/v0.8
- Release v0.8.0-rc4
> Cherry pick pr #858 to release/v0.8

- damocles-worker/src/sealing/paths.rs
- damocles-worker/src/sealing/sealing_thread/planner/common/sealing.rs
close #837
让 PC2 任务可重启。
现在 PC2 即便重启，任务也能正常运行。
> fix(worker): make PC2 tasks restartable

- damocles-worker/Cargo.lock
- damocles-worker/Cargo.toml
- damocles-worker/src/bin/damocles-worker/processor/mod.rs
> feat: supra c2

- damocles-worker/src/sealing/sealing_thread/planner/common/sealing.rs
- damocles-worker/src/sealing/sealing_thread/planner/common/task.rs
> fix(worker): pc2 running file path

- docs/zh/04.damocles-manager的配置解析.md
> 增加token的含义解释 /add description of token

- docs/zh/03.damocles-worker的配置解析.md
> 为worker文档增加token 注释

- damocles-worker/src/sealing/sealing_thread/planner/common.rs
- damocles-worker/src/sealing/sealing_thread/planner/wdpost.rs
> fix(worker): fix sealing Event::State

- CHANGELOG.zh.md
- damocles-manager/ver/ver.go
- damocles-worker/Cargo.lock
- damocles-worker/Cargo.toml
- damocles-worker/src/sealing/sealing_thread/planner/common.rs
- damocles-worker/src/sealing/sealing_thread/planner/wdpost.rs
- Cherry pick #866 to relerase/v0.8
- Release v0.8.0-rc5
> Cherry pick PR #866 to release/v0.8

- damocles-manager/cmd/damocles-manager/internal/util_worker.go
- damocles-manager/core/worker.go
- damocles-worker/Cargo.lock
- damocles-worker/Cargo.toml
- damocles-worker/src/bin/damocles-worker/worker/mod.rs
- damocles-worker/src/rpc/worker/mod.rs
- damocles-worker/src/sealing/sealing_thread/ctrl.rs
- damocles-worker/src/sealing/sealing_thread/planner/common.rs
- damocles-worker/src/sealing/sealing_thread/planner/common/sector.rs
- damocles-worker/src/sealing/sealing_thread/planner/wdpost.rs
- damocles-worker/src/sealing/service.rs
> feat(worker): add stage field

- damocles-manager/dep/gateway.go
- damocles-manager/dep/sealer_constructor.go
- damocles-manager/modules/config.go
- damocles-manager/modules/impl/sectors/unseal_test.go
ref https://github.com/filecoin-project/venus/issues/5561
- modify common api
- set gateway as the default url for chain service
> feat: gateway as default addr for chainService

- damocles-manager/modules/impl/sectors/proving.go
close #728 
每次generatePoSt()方法计算windowpost，都会首先调用checksector进行扇区的检查。现在在checksector方法检查扇区时添加超时机制。当存储出现问题时，checksector会标记这个sector是bad，从而不会计算其windowpost。
但是如果在计算windowpost的过程中，出现存储问题，现在没有超时机制。因为计算windowpost的ffi方法是批量处理很多的sector的，不修改ffi的情况下，无法做到对单个sector进行超时设置。
> add timeout for checking store.state /  检查sector信息时添加超时

- damocles-worker/src/sealing/sealing_thread/planner/common/sealing.rs
> fix(worker): remove treed link file if it exists

- damocles-manager/modules/impl/prover/worker/job_mgr_kv.go
- damocles-manager/modules/impl/prover/worker/job_mgr_kv_test.go
- damocles-worker/src/sealing/sealing_thread/planner/wdpost.rs
> fix(manager): wdpost duplicate alloc

- damocles-worker/src/sealing/sealing_thread/planner/common/sector.rs
> fix: stage name

- CHANGELOG.zh.md
- damocles-manager/modules/impl/prover/worker/job_mgr_kv.go
- damocles-manager/modules/impl/prover/worker/job_mgr_kv_test.go
- damocles-manager/ver/ver.go
- damocles-worker/Cargo.lock
- damocles-worker/Cargo.toml
- damocles-worker/src/sealing/paths.rs
- damocles-worker/src/sealing/sealing_thread/planner/common/sealing.rs
- damocles-worker/src/sealing/sealing_thread/planner/common/task.rs
- damocles-worker/src/sealing/sealing_thread/planner/wdpost.rs
- Cherry pick PR #876 #877 #860 #863 to release/v0.8
- Release v0.8.0-rc6
> Cherry pick PR #876 #877 #860 #863 to release/v0.8

- damocles-worker/src/sealing/sealing_thread/planner/common/sector.rs
> fix(worker): stage name

- damocles-manager/core/types.go
- damocles-manager/go.mod
- damocles-manager/go.sum
- damocles-manager/modules/impl/dealmgr/dealmgr.go
- damocles-manager/modules/sealer/sealer.go
ref https://github.com/ipfs-force-community/droplet/pull/404
分配订单必须满足条件：
参考 builtin-actor 代码：
- https://github.com/filecoin-project/builtin-actors/blob/c0aed11801cb434c989695ad67721c410b9ada33/actors/market/src/lib.rs#L1073-L1094
- https://github.com/filecoin-project/builtin-actors/blob/c0aed11801cb434c989695ad67721c410b9ada33/actors/verifreg/src/lib.rs#L1056-L1071
> fix(manager): snapdeal: filter deals by sector expiration

- damocles-worker/vc-processors/src/core/ext/producer.rs
> fix(worker): subprocess envs override the main process

- damocles-worker/src/logging/mod.rs
> feat(worker): remove jsonrpc log

- damocles-worker/Dockerfile
> fix(docker: worker): expose 17891 -> expose 17890

- CHANGELOG.zh.md
- damocles-manager/core/types.go
- damocles-manager/go.mod
- damocles-manager/go.sum
- damocles-manager/modules/impl/dealmgr/dealmgr.go
- damocles-manager/modules/sealer/sealer.go
- damocles-manager/ver/ver.go
- damocles-worker/Cargo.lock
- damocles-worker/Cargo.toml
- damocles-worker/Dockerfile
- damocles-worker/src/logging/mod.rs
- damocles-worker/vc-processors/src/core/ext/producer.rs
- Cherry-pick #889 #892 #890 #887 #885 to release/v0.8
- Release v0.8.0
> Cherry pick #889 #892 #890 #887 #885 to release/v0.8

- damocles-worker/src/bin/damocles-worker/store.rs
- damocles-worker/src/sealing/sealing_thread/mod.rs
- damocles-worker/src/sealing/store/mod.rs
- docs/zh/05.快速启用.md
close #899
自动初始化 sealing_thread 目录
> feat(worker): auto create sealing_thread dirs

- damocles-worker/src/bin/damocles-worker/processor/mod.rs
- damocles-worker/vc-processors/src/builtin/processors.rs
- damocles-worker/vc-processors/src/builtin/processors/transfer/mod.rs
> feat(worker): support disable link

- damocles-manager/core/api.go
- damocles-manager/core/client_gen.go
- damocles-manager/core/types.go
- damocles-manager/modules/impl/mock/sealer.go
- damocles-manager/modules/sealer/sealer.go
- damocles-worker/src/lib.rs
- damocles-worker/src/rpc/sealer/mod.rs
- damocles-worker/src/sealing/sealing_thread/mod.rs
- damocles-worker/src/sealing/sealing_thread/planner/common.rs
- damocles-worker/src/sealing/sealing_thread/planner/common/task.rs
…er's state
close #737
封装时，每个阶段都会调用一下report_state接口，给manager汇报自己的状态，接口返回manager的sector的状态。
如果manager 的sector状态已经是finalized的话，就终止封装任务。
> `worker`汇报状态时，获取`manager`的sector状态，如果是finalized的话，就终止`worker`自身的封装。

- damocles-worker/Cargo.lock
> bump storage-proofs-porep to fix cpuset bug

- CHANGELOG.zh.md
- damocles-manager/ver/ver.go
- damocles-worker/Cargo.lock
- damocles-worker/Cargo.toml
- Cherry-pick #904 to release/v0.8
- Release v0.8.1
> Cherry-pick #904 to release/v0.8

- damocles-worker/src/bin/damocles-worker/worker/mod.rs
- damocles-worker/src/sealing/sealing_thread/planner/wdpost.rs
> chore: escape error message

- damocles-manager/pkg/logging/log.go
> feat(manager): always mute kv log

- damocles-manager/pkg/logging/log.go
> feat(manager): always mute rpc log

- damocles-worker/Cargo.lock
- damocles-worker/Cargo.toml
- damocles-worker/src/bin/damocles-worker/processor/mod.rs
> remove supra code

- CHANGELOG.zh.md
- damocles-manager/ver/ver.go
- damocles-worker/Cargo.lock
- damocles-worker/Cargo.toml
- damocles-worker/src/bin/damocles-worker/processor/mod.rs
- damocles-worker/vc-processors/src/builtin/processors.rs
- damocles-worker/vc-processors/src/builtin/processors/transfer/mod.rs
#901
- Cherry-pick #901 to release/v0.8
- Release v0.8.2
> Cherry-pick #901 to release/v0.8

- docs/en/09.poster-node.md
- docs/zh/09.独立运行的poster节点.md
> docs(09): disable gpu

- docs/en/09.poster-node.md
- docs/zh/09.独立运行的poster节点.md
> doc(09): add `make dist-clean`

- damocles-worker/Cargo.lock
- damocles-worker/Cargo.toml
- damocles-worker/src/bin/damocles-worker/processor/mod.rs
Reverts ipfs-force-community/damocles#910
> Revert "remove supra code"

- docs/en/09.poster-node.md
- docs/zh/09.独立运行的poster节点.md
> 0x5459 patch 1

- damocles-manager/modules/impl/sectors/snapup_commit.go
> chore: log store instance

- damocles-manager/cmd/damocles-manager/server.go
- damocles-manager/go.mod
- damocles-manager/go.sum
> feat: add health api

- damocles-manager/pkg/logging/log.go
> feat(manager): set log level if not set

- manager-plugin/objstore/objstore.go
> chore: add some necessary comments

- damocles-manager/modules/impl/sectors/proving.go
> feat(manager): do not check filesize

- damocles-manager/core/types.go
- damocles-worker/vc-processors/src/builtin/processors/transfer/mod.rs
> fix(worker): fix field name

- docs/en/09.poster-node.md
- docs/zh/09.独立运行的poster节点.md
> doc(09): add TMPDIR env

- damocles-manager/cmd/damocles-manager/internal/util_worker.go
- damocles-manager/core/api.go
- damocles-manager/core/client_gen.go
- damocles-manager/core/types_wdpost.go
- damocles-manager/modules/impl/prover/worker/rpc.go
> feat(wdpost): show max try if tryNum reaching max

- damocles-manager/modules/impl/prover/worker/rpc.go
> fix(wdpost: di): fix dep

- docs/en/04.damocles-manager-config.md
- docs/zh/04.damocles-manager的配置解析.md
> doc: doc about unit entry

- damocles-manager/modules/impl/prover/ext/prover.go
> fix(manager): Invalid commitment (randomness)

- CHANGELOG.zh.md
- damocles-manager/modules/impl/prover/ext/prover.go
- damocles-manager/ver/ver.go
- damocles-worker/Cargo.lock
- damocles-worker/Cargo.toml
- Cherry pick #943 to release v0.8
- Release v0.8.4
> Cherry pick #943 to release v0.8

- docs/zh/17. damocles与lotus-miner切换流程.md
> add address of reference / 添加参考信息的跳转地址

- damocles-manager/dep/gateway.go
- damocles-manager/dep/sealer_constructor.go
> fix: make error for droplet tolerated

- Makefile
允许分别构建和推送 worker 和 manager 的 docker 镜像
> chore(docker): allow pushing docker images separately

- docs/zh/05.快速启用.md
> add more deployment details / 添加更多部署的详细信息

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/enhancement.yml
- 移除 issue template 里面的 component 模块
> chore: remove components in issue template

- docs/en/06.migrate-sectors-to-damocles.md
- docs/zh/06.导入已存在的扇区数据.md
> doc: rm duplicate flag in attach doc

- damocles-manager/cmd/damocles-manager/internal/util_storage.go
> feat(mgr: cli): support setting attach pattern

- damocles-manager/cmd/damocles-manager/internal/util_storage.go
> doc: improve attach usage

- CHANGELOG.zh.md
- damocles-manager/ver/ver.go
- damocles-worker/Cargo.lock
- damocles-worker/Cargo.toml
> chore: working on v0.9

- damocles-manager/modules/sealer/sealer.go
> fix(mgr): clear upgrade state when sector aborted

- damocles-manager/pkg/kvstore/badger.go
> feat(manager): auto gc badger db

- damocles-manager/modules/impl/prover/worker/prover.go
> chore: add comment

- damocles-manager/cmd/damocles-manager/internal/global.go
- damocles-manager/cmd/damocles-manager/internal/util_miner.go
- docs/zh/05.快速启用.md
> chore(cli: miner create): just print miner id

- docs/en/12.damocles-worker-config-guide.md
- docs/zh/12.damocles-worker-配置指北.md
> doc(12): add damocles-worker configuration guide

- docs/en/12.damocles-worker-config-guide.md
- docs/zh/12.damocles-worker-配置指北.md
> doc(12): fix typo

- damocles-manager/cmd/damocles-manager/internal/util_sealer_proving.go
simulate-wdpost 允许设置 challenge
> feat(cli): simulate-wdpost allows specify the challenge

- damocles-manager/cmd/damocles-manager/internal/util_miner.go
- damocles-manager/cmd/damocles-manager/internal/util_sealer_sectors.go
- damocles-manager/go.mod
- damocles-manager/go.sum
- damocles-manager/modules/impl/commitmgr/policy.go
- damocles-manager/modules/impl/sectors/snapup_commit.go
- damocles-manager/pkg/chain/miner_api.go
close https://github.com/ipfs-force-community/damocles/issues/977
> feat: add cli to move partitions

- damocles-manager/pkg/piecestore/proxy.go
- damocles-manager/pkg/piecestore/proxy_test.go
- damocles-worker/src/infra/piecestore/local.rs
> feat(piece): support dot car filename

- docs/en/09.poster-node.md
- docs/zh/09.独立运行的poster节点.md
> doc(09): add some example

- docs/zh/17. damocles与lotus-miner切换流程.md
update lotus-miner config info
> Update 17. damocles与lotus-miner切换流程.md

- damocles-manager/modules/impl/commitmgr/check.go
- damocles-manager/modules/impl/commitmgr/sealing.go
> feat: use StateComputeDataCID from node

- damocles-manager/modules/poster/poster_test.go
- damocles-manager/modules/poster/runner_test.go
- damocles-manager/pkg/chain/api.go
> fix: network version shaddowed

- damocles-worker/vc-processors/src/core/ext/producer.rs
> chore: improve subprocess error message

- damocles-manager/cmd/damocles-manager/internal/util_sealer_sectors.go
> chore(cli): rename flag: actor -> miner

- damocles-worker/src/rpc/worker/mod.rs
- damocles-worker/src/sealing/sealing_thread/ctrl.rs
> feat: make running.proc optional

- damocles-worker/Cargo.lock
- damocles-worker/Cargo.toml
> bump rocksdb: v0.21.0

- damocles-manager/core/types.go
- damocles-manager/modules/impl/commitmgr/precommit_processor.go
> feat: make precommit configurable

- damocles-worker/Cargo.lock
- damocles-worker/src/bin/damocles-worker/processor/mod.rs
- damocles-worker/vc-processors/Cargo.toml
> fix(dep): conditional compilation errors

- CHANGELOG.zh.md
- damocles-manager/ver/ver.go
- damocles-worker/Cargo.lock
- damocles-worker/Cargo.toml
> chore: release v0.9.0-rc1

- CHANGELOG.zh.md
- damocles-manager/ver/ver.go
- damocles-worker/Cargo.lock
- damocles-worker/Cargo.toml
> Working on v0.10

- damocles-worker/Cargo.toml
- damocles-worker/src/bin/damocles-worker/processor/mod.rs
> fix(dep): conditional compilation error

- CHANGELOG.zh.md
- damocles-manager/ver/ver.go
- damocles-worker/Cargo.lock
- damocles-worker/Cargo.toml
- damocles-worker/src/bin/damocles-worker/processor/mod.rs
ref #1004
- cherry-pick #1004 to release/v0.9
- release v0.9.0-rc2
> Cherry pick pr #1004 to release v0.9

- CHANGELOG.zh.md
- damocles-manager/modules/impl/commitmgr/precommit_processor.go
> fix: ref local var of sector state

- CHANGELOG.zh.md
- damocles-manager/modules/impl/commitmgr/precommit_processor.go
…t-cid
fix: ref local var of sector state
> chore: pick #1006

- damocles-manager/ver/ver.go
- damocles-worker/Cargo.lock
- damocles-worker/Cargo.toml
> feat: bump up version to v0.9.0-rc3

- CHANGELOG.zh.md
- damocles-manager/modules/config.go
- damocles-manager/modules/config_util.go
- damocles-manager/modules/config_util_test.go
- damocles-manager/modules/impl/commitmgr/commit_processor.go
- damocles-manager/modules/impl/commitmgr/precommit_processor.go
- damocles-manager/modules/impl/commitmgr/processor.go
- damocles-manager/modules/impl/commitmgr/terminate_processor.go
- damocles-manager/ver/ver.go
- damocles-worker/Cargo.lock
- damocles-worker/Cargo.toml
- docs/en/04.damocles-manager-config.md
- docs/zh/04.damocles-manager的配置解析.md
> Chore/pick #1012 & bump up version to v0.9.0 rc4

- damocles-manager/go.mod
- damocles-manager/go.sum
> chore(deps): bump github.com/filecoin-project/venus from v1.14.0-rc3 to v1.14.0-rc4

- CHANGELOG.zh.md
- damocles-manager/go.mod
- damocles-manager/go.sum
- damocles-manager/ver/ver.go
- damocles-worker/Cargo.lock
- damocles-worker/Cargo.toml
ref #1016
- Cherry pick #1016 to release v0.9
- Release v0.9.0-rc5
> Cherry pick #1016 to release v0.9

- CHANGELOG.zh.md
- damocles-manager/cmd/damocles-manager/internal/util_storage.go
- damocles-manager/dep/sealer_constructor.go
- damocles-manager/go.mod
- damocles-manager/go.sum
- damocles-manager/modules/config.go
- damocles-manager/modules/config_util.go
- damocles-manager/modules/config_util_test.go
- damocles-manager/modules/sealer/sealer_cli.go
- damocles-manager/pkg/objstore/filestore/store.go
- damocles-manager/pkg/objstore/mgr.go
- damocles-manager/pkg/objstore/mgr_test.go
- damocles-manager/pkg/objstore/mock_store.go
- damocles-manager/pkg/piecestore/proxy.go
- damocles-manager/ver/ver.go
- damocles-worker/Cargo.lock
- damocles-worker/Cargo.toml
- damocles-worker/assets/damocles-worker.mock.toml
- damocles-worker/src/config.rs
- damocles-worker/src/run.rs
- docs/en/03.damocles-worker-config.md
- docs/en/04.damocles-manager-config.md
- docs/zh/03.damocles-worker的配置解析.md
- docs/zh/04.damocles-manager的配置解析.md
- docs/zh/19.damocles-扇区存储配置.md
- manager-plugin/objstore/objstore.go
ref #1019 
- Cherry-pick pr #1019 to release v0.9
- Release v0.9.0-rc6
> Cherry pick #1019 to release v0.9

- CHANGELOG.zh.md
- damocles-manager/cmd/damocles-manager/internal/global.go
- damocles-manager/cmd/damocles-manager/internal/util_sealer_proving.go
do not wait for message if message fails
修复 wait for message, 如果消息失败了则不继续等待消息而是直接返回错误
> fix(manager: cli): wait for message

- CHANGELOG.zh.md
- damocles-manager/cmd/damocles-manager/internal/util_sealer_sectors.go
> feat: comment utilSealerSectorsMovePartitionsCmd

- damocles-manager/go.mod
- damocles-manager/go.sum
> bump version: venus, lotus

- damocles-manager/modules/impl/prover/worker/job_mgr_kv.go
wdpost 任务允许向 ReadytoRun 状态的任务发送心跳，并将任务重新设置为 running。
manager 重启可能导致任务心跳超时，manager启动会将心跳超时的任务重新设置为 ReadyToRun。导致 worker 发送正在做的任务心跳会找不到对应的任务
> feat(wdpost): allow heartbeat ReadytoRun jobs

- CHANGELOG.zh.md
- damocles-manager/cmd/damocles-manager/internal/global.go
- damocles-manager/cmd/damocles-manager/internal/util_sealer_proving.go
- damocles-manager/cmd/damocles-manager/internal/util_sealer_sectors.go
- damocles-manager/go.mod
- damocles-manager/go.sum
- damocles-manager/modules/impl/prover/worker/job_mgr_kv.go
- damocles-manager/ver/ver.go
- damocles-worker/Cargo.lock
- damocles-worker/Cargo.toml
- Cherry pick #1022 #1024 #1027 #1028 to release v0.9
- Release v0.9.0-rc7
> Cherry pick #1022 #1024 #1027 #1028 to release v0.9

- damocles-manager/cmd/damocles-manager/internal/util_worker.go
优化 wdpost list partitions 字段输出显示
> chore: improve wdpost list partitions output

- CHANGELOG.zh.md
- damocles-worker/src/infra/piecestore/local.rs
检查标准文件是否存在。避免出现一些特殊文件系统将不存在的文件返回成文件夹的行为。
> feat(worker): check the regular file exists

- manager-plugin/examples/concurrent-limiter/README.md
> doc: fix typo

- damocles-manager/modules/impl/sectors/snapup_commit.go
> fix(manager): print del error

- CHANGELOG.zh.md
- damocles-worker/vc-processors/src/builtin/processors/piece/fetcher/http.rs
> fix: supply api name space header

- CHANGELOG.zh.md
- damocles-manager/modules/impl/commitmgr/terminate_processor.go
> fix: check enable before terminate batch

- CHANGELOG.zh.md
- damocles-manager/dep/sealer.go
- damocles-manager/dep/sealer_constructor.go
- damocles-manager/modules/config.go
- damocles-manager/ver/ver.go
- damocles-worker/Cargo.lock
- damocles-worker/Cargo.toml
ref #1046 #1047
- Cherry pick #1046 #1047 to release v0.9
- Release v0.9.2
> Cherry pick #1046 #1047 to release v0.9

- CHANGELOG.zh.md
- damocles-manager/cmd/damocles-manager/internal/util_sealer_actor.go
- damocles-manager/core/ifaces.go
- damocles-manager/dep/poster.go
- damocles-manager/dep/sealer.go
- damocles-manager/dep/sealer_constructor.go
- damocles-manager/go.mod
- damocles-manager/go.sum
- damocles-manager/modules/config.go
- damocles-manager/modules/impl/commitmgr/commitmgr.go
- damocles-manager/modules/impl/sectors/sender_selector.go
- damocles-manager/modules/impl/sectors/sender_selector_test.go
- damocles-manager/modules/impl/sectors/snapup_commit.go
- damocles-manager/modules/impl/sectors/snapup_mgr.go
- damocles-manager/modules/poster/poster.go
- damocles-manager/modules/poster/poster_test.go
- damocles-manager/modules/poster/runner.go
- docs/en/04.damocles-manager-config.md
- docs/zh/04.damocles-manager的配置解析.md
close #1045
支持配置多个 sender 地址，选择其中一个有效的且余额最多的地址作为发送地址
> feat(manager): support multiple senders

- CHANGELOG.zh.md
- damocles-manager/modules/impl/prover/worker/job_mgr_kv.go
> fix: donot allow heartbeat to finished tasks

- damocles-manager/modules/impl/commitmgr/precommit_processor.go
> fix: use fee config for batch when batch pre commit

- CHANGELOG.zh.md
- damocles-manager/cmd/damocles-manager/internal/util_sealer_actor.go
- damocles-manager/core/ifaces.go
- damocles-manager/dep/poster.go
- damocles-manager/dep/sealer.go
- damocles-manager/dep/sealer_constructor.go
- damocles-manager/go.mod
- damocles-manager/go.sum
- damocles-manager/modules/config.go
- damocles-manager/modules/impl/commitmgr/commitmgr.go
- damocles-manager/modules/impl/sectors/sender_selector.go
- damocles-manager/modules/impl/sectors/sender_selector_test.go
- damocles-manager/modules/impl/sectors/snapup_commit.go
- damocles-manager/modules/impl/sectors/snapup_mgr.go
- damocles-manager/modules/poster/poster.go
- damocles-manager/modules/poster/poster_test.go
- damocles-manager/modules/poster/runner.go
- docs/en/04.damocles-manager-config.md
- docs/zh/04.damocles-manager的配置解析.md
…t-mutil-senders
feat(manager): support multiple senders
> chore: pick-1051-to-v0.9

- damocles-worker/src/sealing/sealing_thread/planner/wdpost.rs
> feat: upgrade log level of wdpost allocating

- CHANGELOG.zh.md
- damocles-worker/src/config.rs
- damocles-worker/src/sealing/config.rs
- damocles-worker/src/sealing/sealing_thread/planner/common/sealing.rs
- damocles-worker/src/sealing/sealing_thread/planner/rebuild.rs
- damocles-worker/src/sealing/sealing_thread/planner/sealer.rs
- docs/en/03.damocles-worker-config.md
- docs/zh/03.damocles-worker的配置解析.md
> feat: verify pc2

- damocles-manager/cmd/damocles-manager/internal/util_sealer_sectors.go
> chore(cli): remove redundant code

- damocles-manager/cmd/damocles-manager/internal/util_sealer_sectors.go
- docs/en/17.switching-between-damocles-and-lotus-miner.md
- docs/zh/17. damocles与lotus-miner切换流程.md
> feat(cli): support import & export sector state in json format

- CHANGELOG.zh.md
- damocles-manager/ver/ver.go
- damocles-worker/Cargo.lock
- damocles-worker/Cargo.toml
> chore: release v0.10.0-rc1

- damocles-manager/core/types.go
> fix: get EndEpoch correctly in legacy deals

- CHANGELOG.zh.md
- damocles-worker/src/config.rs
- damocles-worker/src/run.rs
- damocles-worker/src/watchdog.rs
- damocles-worker/vc-processors/src/builtin/processors.rs
- damocles-worker/vc-processors/src/core/mod.rs
- docs/en/03.damocles-worker-config.md
- docs/zh/03.damocles-worker的配置解析.md
> feat(worker): support custom sealing daemon processor

- damocles-manager/modules/sealer/sealer.go
> chore(snapup): add more logs

- damocles-manager/modules/impl/commitmgr/commit_processor.go
> feat: remove ProveCommitSector method

- damocles-worker/src/sealing/sealing_thread/planner/niporep.rs
- damocles-worker/src/types.rs
> fix(niporep-planner): transfer  seal proofto ni porep type

- CHANGELOG.zh.md
- damocles-manager/go.mod
- damocles-manager/go.sum
- damocles-manager/ver/ver.go
> Chore/bump v0.11.0

- damocles-manager/modules/impl/sectors/snapup_commit.go
> fix: incorrect sender address in snapup

- damocles-manager/.golangci.yml
- damocles-manager/modules/impl/commitmgr/params.go
> make lint happy

- damocles-manager/go.mod
- damocles-manager/go.sum
> chore: bump venus & ffi version

- damocles-worker/Cargo.toml
- damocles-worker/src/sealing/sealing_thread/mod.rs
Auto resume when SealingThread sealing failed
> feat: SealingThread auto resume when sealing failed

- damocles-worker/Cargo.toml
- damocles-worker/src/sealing/sealing_thread/mod.rs
> chore: rename auto_resume feature to auto-resume

- damocles-manager/go.mod
- damocles-manager/go.sum
> chore: update ffi & venus
